# Generated by Django 5.0.1 on 2025-10-16 18:22

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaCorrienteCliente',
            fields=[
                ('ven_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ven_fecha', models.DateField()),
                ('ven_idcli', models.IntegerField()),
                ('comprobante_nombre', models.CharField(max_length=50)),
                ('comprobante_tipo', models.CharField(max_length=30)),
                ('debe', models.DecimalField(decimal_places=2, max_digits=15)),
                ('haber', models.DecimalField(decimal_places=2, max_digits=15)),
                ('saldo_acumulado', models.DecimalField(decimal_places=2, max_digits=15)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ven_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('numero_formateado', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'CUENTA_CORRIENTE_CLIENTE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImputacionVenta',
            fields=[
                ('imp_id', models.AutoField(db_column='IMP_ID', primary_key=True, serialize=False)),
                ('imp_fecha', models.DateField(db_column='IMP_FECHA')),
                ('imp_monto', models.DecimalField(db_column='IMP_MONTO', decimal_places=2, help_text='Monto imputado de la factura', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('imp_observacion', models.CharField(blank=True, db_column='IMP_OBSERVACION', help_text='Observaciones sobre la imputación', max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Imputación de Venta',
                'verbose_name_plural': 'Imputaciones de Ventas',
                'db_table': 'IMPUTACION_VENTA',
            },
        ),
    ]
