# Generated by Django 5.0.1 on 2025-10-16 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuenta_corriente', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imputacionventa',
            name='imp_id_recibo',
            field=models.ForeignKey(db_column='IMP_ID_RECIBO', help_text='Recibo o crédito que está realizando la imputación', on_delete=django.db.models.deletion.PROTECT, related_name='imputaciones_realizadas', to='ventas.venta'),
        ),
        migrations.AddField(
            model_name='imputacionventa',
            name='imp_id_venta',
            field=models.ForeignKey(db_column='IMP_ID_VENTA', help_text='Factura que está siendo imputada', on_delete=django.db.models.deletion.PROTECT, related_name='imputaciones_recibidas', to='ventas.venta'),
        ),
        migrations.AddIndex(
            model_name='imputacionventa',
            index=models.Index(fields=['imp_id_venta'], name='IMPUTACION__IMP_ID__1c6fe2_idx'),
        ),
        migrations.AddIndex(
            model_name='imputacionventa',
            index=models.Index(fields=['imp_id_recibo'], name='IMPUTACION__IMP_ID__6155ee_idx'),
        ),
        migrations.AddIndex(
            model_name='imputacionventa',
            index=models.Index(fields=['imp_fecha'], name='IMPUTACION__IMP_FEC_72ba9a_idx'),
        ),
        migrations.AddIndex(
            model_name='imputacionventa',
            index=models.Index(fields=['imp_id_venta', 'imp_fecha'], name='IMPUTACION__IMP_ID__76013b_idx'),
        ),
        migrations.AddConstraint(
            model_name='imputacionventa',
            constraint=models.CheckConstraint(check=models.Q(('imp_monto__gt', 0)), name='imp_monto_positivo'),
        ),
        migrations.AlterUniqueTogether(
            name='imputacionventa',
            unique_together={('imp_id_venta', 'imp_id_recibo', 'imp_fecha')},
        ),
    ]
