# Generated by Django 5.0.1 on 2025-10-08 08:02

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta_corriente', '0002_recrear_vista_cc'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='imputacionventa',
            new_name='IMPUTACION__IMP_ID__1c6fe2_idx',
            old_name='imputacion_venta_idx',
        ),
        migrations.RenameIndex(
            model_name='imputacionventa',
            new_name='IMPUTACION__IMP_ID__6155ee_idx',
            old_name='imputacion_recibo_idx',
        ),
        migrations.RenameIndex(
            model_name='imputacionventa',
            new_name='IMPUTACION__IMP_FEC_72ba9a_idx',
            old_name='imputacion_fecha_idx',
        ),
        migrations.RenameIndex(
            model_name='imputacionventa',
            new_name='IMPUTACION__IMP_ID__76013b_idx',
            old_name='imputacion_venta_fecha_idx',
        ),
        migrations.AlterField(
            model_name='imputacionventa',
            name='imp_monto',
            field=models.DecimalField(db_column='IMP_MONTO', decimal_places=2, help_text='Monto imputado de la factura', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='imputacionventa',
            name='imp_observacion',
            field=models.CharField(blank=True, db_column='IMP_OBSERVACION', help_text='Observaciones sobre la imputación', max_length=200, null=True),
        ),
    ]
