# Generated by Django 5.0.1 on 2025-10-09 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta_corriente', '0003_rename_imputacion_venta_idx_imputacion__imp_id__1c6fe2_idx_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='imputacionventa',
            name='no_autoimputacion_directa',
        ),
    ]
