# Generated by Django 5.0.1 on 2026-02-10 19:50

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0011_cheque_comision_cambio_and_more'),
        ('compras', '0001_initial'),
        ('cuenta_corriente', '0003_corregir_nc_nd_internas'),
        ('productos', '0013_stock_impuesto_interno_porcentaje'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaCorrienteProveedor',
            fields=[
                ('comp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('comp_fecha', models.DateField()),
                ('comp_proveedor', models.IntegerField()),
                ('comprobante_nombre', models.CharField(max_length=50)),
                ('comprobante_tipo', models.CharField(max_length=30)),
                ('debe', models.DecimalField(decimal_places=2, max_digits=15)),
                ('haber', models.DecimalField(decimal_places=2, max_digits=15)),
                ('saldo_acumulado', models.DecimalField(decimal_places=2, max_digits=15)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, max_digits=15)),
                ('comp_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('numero_formateado', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'CUENTA_CORRIENTE_PROVEEDOR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenPago',
            fields=[
                ('op_id', models.AutoField(db_column='OP_ID', primary_key=True, serialize=False)),
                ('op_fecha', models.DateField(db_column='OP_FECHA')),
                ('op_numero', models.CharField(db_column='OP_NUMERO', help_text='Número de orden de pago (formato: 0001-00000001)', max_length=20, unique=True)),
                ('op_total', models.DecimalField(db_column='OP_TOTAL', decimal_places=2, help_text='Monto total de la orden de pago', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('op_observacion', models.CharField(blank=True, db_column='OP_OBSERVACION', help_text='Observaciones de la orden de pago', max_length=200, null=True)),
                ('op_fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='OP_FECHA_CREACION')),
                ('op_estado', models.CharField(choices=[('A', 'Activo'), ('N', 'Anulado')], db_column='OP_ESTADO', default='A', max_length=1)),
                ('op_proveedor', models.ForeignKey(db_column='OP_PROVEEDOR', help_text='Proveedor al que se le paga', on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_pago', to='productos.proveedor')),
                ('op_usuario', models.ForeignKey(db_column='OP_USUARIO', help_text='Usuario que creó la orden de pago', on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_pago_creadas', to=settings.AUTH_USER_MODEL)),
                ('sesion_caja', models.ForeignKey(blank=True, db_column='OP_SESION_CAJA', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_pago', to='caja.sesioncaja')),
            ],
            options={
                'verbose_name': 'Orden de Pago',
                'verbose_name_plural': 'Órdenes de Pago',
                'db_table': 'ORDEN_PAGO',
            },
        ),
        migrations.CreateModel(
            name='ImputacionCompra',
            fields=[
                ('imp_id', models.AutoField(db_column='IMP_ID', primary_key=True, serialize=False)),
                ('imp_fecha', models.DateField(db_column='IMP_FECHA')),
                ('imp_monto', models.DecimalField(db_column='IMP_MONTO', decimal_places=2, help_text='Monto imputado de la compra', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('imp_observacion', models.CharField(blank=True, db_column='IMP_OBSERVACION', help_text='Observaciones sobre la imputación', max_length=200, null=True)),
                ('imp_id_compra', models.ForeignKey(db_column='IMP_ID_COMPRA', help_text='Compra que está siendo imputada', on_delete=django.db.models.deletion.PROTECT, related_name='imputaciones_recibidas', to='compras.compra')),
                ('imp_id_orden_pago', models.ForeignKey(db_column='IMP_ID_ORDEN_PAGO', help_text='Orden de pago que está realizando la imputación', on_delete=django.db.models.deletion.PROTECT, related_name='imputaciones_realizadas', to='cuenta_corriente.ordenpago')),
            ],
            options={
                'verbose_name': 'Imputación de Compra',
                'verbose_name_plural': 'Imputaciones de Compras',
                'db_table': 'IMPUTACION_COMPRA',
            },
        ),
        migrations.AddIndex(
            model_name='ordenpago',
            index=models.Index(fields=['op_fecha'], name='ORDEN_PAGO_OP_FECH_599dea_idx'),
        ),
        migrations.AddIndex(
            model_name='ordenpago',
            index=models.Index(fields=['op_proveedor'], name='ORDEN_PAGO_OP_PROV_b9b704_idx'),
        ),
        migrations.AddIndex(
            model_name='ordenpago',
            index=models.Index(fields=['op_estado'], name='ORDEN_PAGO_OP_ESTA_e11983_idx'),
        ),
        migrations.AddConstraint(
            model_name='ordenpago',
            constraint=models.CheckConstraint(check=models.Q(('op_total__gt', 0)), name='op_total_positivo'),
        ),
        migrations.AddIndex(
            model_name='imputacioncompra',
            index=models.Index(fields=['imp_id_compra'], name='IMPUTACION__IMP_ID__7f9982_idx'),
        ),
        migrations.AddIndex(
            model_name='imputacioncompra',
            index=models.Index(fields=['imp_id_orden_pago'], name='IMPUTACION__IMP_ID__a58b63_idx'),
        ),
        migrations.AddIndex(
            model_name='imputacioncompra',
            index=models.Index(fields=['imp_fecha'], name='IMPUTACION__IMP_FEC_576e34_idx'),
        ),
        migrations.AddConstraint(
            model_name='imputacioncompra',
            constraint=models.CheckConstraint(check=models.Q(('imp_monto__gt', 0)), name='imp_compra_monto_positivo'),
        ),
        migrations.AlterUniqueTogether(
            name='imputacioncompra',
            unique_together={('imp_id_compra', 'imp_id_orden_pago', 'imp_fecha')},
        ),
    ]
