# Generated by Django 5.0.1 on 2026-02-12 21:29

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta_corriente', '0005_crear_vista_cc_proveedor'),
        ('productos', '0013_stock_impuesto_interno_porcentaje'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteProveedor',
            fields=[
                ('aj_id', models.AutoField(db_column='AJ_ID', primary_key=True, serialize=False)),
                ('aj_tipo', models.CharField(choices=[('DEBITO', 'Ajuste Débito'), ('CREDITO', 'Ajuste Crédito')], db_column='AJ_TIPO', help_text='Tipo de ajuste: DEBITO o CREDITO', max_length=10)),
                ('aj_fecha', models.DateField(db_column='AJ_FECHA', help_text='Fecha del comprobante de ajuste')),
                ('aj_numero', models.CharField(db_column='AJ_NUMERO', help_text='Número del comprobante externo (PV-Número)', max_length=30)),
                ('aj_monto', models.DecimalField(db_column='AJ_MONTO', decimal_places=2, help_text='Monto del ajuste', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('aj_observacion', models.TextField(blank=True, db_column='AJ_OBSERVACION', default='', help_text='Motivo u observaciones del ajuste')),
                ('aj_estado', models.CharField(choices=[('A', 'Activo'), ('X', 'Anulado')], db_column='AJ_ESTADO', default='A', max_length=1)),
                ('aj_fecha_registro', models.DateTimeField(auto_now_add=True, db_column='AJ_FECHA_REGISTRO')),
                ('aj_proveedor', models.ForeignKey(db_column='AJ_PROVEEDOR', help_text='Proveedor al que corresponde el ajuste', on_delete=django.db.models.deletion.PROTECT, related_name='ajustes', to='productos.proveedor')),
                ('aj_usuario', models.ForeignKey(db_column='AJ_USUARIO', help_text='Usuario que registró el ajuste', on_delete=django.db.models.deletion.PROTECT, related_name='ajustes_proveedor_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ajuste de Proveedor',
                'verbose_name_plural': 'Ajustes de Proveedores',
                'db_table': 'AJUSTE_PROVEEDOR',
                'indexes': [models.Index(fields=['aj_fecha'], name='AJUSTE_PROV_AJ_FECH_b09a0f_idx'), models.Index(fields=['aj_proveedor'], name='AJUSTE_PROV_AJ_PROV_56646e_idx'), models.Index(fields=['aj_tipo'], name='AJUSTE_PROV_AJ_TIPO_e5375b_idx'), models.Index(fields=['aj_estado'], name='AJUSTE_PROV_AJ_ESTA_82d35b_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='ajusteproveedor',
            constraint=models.CheckConstraint(check=models.Q(('aj_monto__gt', 0)), name='aj_monto_positivo'),
        ),
    ]
