# Generated by Django 5.0.1 on 2026-02-13 04:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('cuenta_corriente', '0008_drop_sql_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imputacion',
            fields=[
                ('imp_id', models.AutoField(db_column='IMP_ID', primary_key=True, serialize=False)),
                ('origen_id', models.PositiveIntegerField(db_column='ORIGEN_ID')),
                ('destino_id', models.PositiveIntegerField(db_column='DESTINO_ID')),
                ('imp_fecha', models.DateField(db_column='IMP_FECHA')),
                ('imp_monto', models.DecimalField(db_column='IMP_MONTO', decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('imp_observacion', models.CharField(blank=True, db_column='IMP_OBSERVACION', default='', max_length=200)),
                ('destino_content_type', models.ForeignKey(db_column='DESTINO_CT_ID', on_delete=django.db.models.deletion.CASCADE, related_name='imputaciones_como_destino', to='contenttypes.contenttype')),
                ('origen_content_type', models.ForeignKey(db_column='ORIGEN_CT_ID', on_delete=django.db.models.deletion.CASCADE, related_name='imputaciones_como_origen', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Imputación',
                'verbose_name_plural': 'Imputaciones',
                'db_table': 'IMPUTACION',
            },
        ),
        migrations.AlterUniqueTogether(
            name='imputacioncompra',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='imputacioncompra',
            name='imp_id_compra',
        ),
        migrations.RemoveField(
            model_name='imputacioncompra',
            name='imp_id_orden_pago',
        ),
        migrations.AlterUniqueTogether(
            name='imputacionventa',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='imputacionventa',
            name='imp_id_recibo',
        ),
        migrations.RemoveField(
            model_name='imputacionventa',
            name='imp_id_venta',
        ),
        migrations.DeleteModel(
            name='CuentaCorrienteCliente',
        ),
        migrations.DeleteModel(
            name='CuentaCorrienteProveedor',
        ),
        migrations.DeleteModel(
            name='ImputacionCompra',
        ),
        migrations.DeleteModel(
            name='ImputacionVenta',
        ),
        migrations.AddIndex(
            model_name='imputacion',
            index=models.Index(fields=['origen_content_type', 'origen_id'], name='IMPUTACION_ORIGEN__392960_idx'),
        ),
        migrations.AddIndex(
            model_name='imputacion',
            index=models.Index(fields=['destino_content_type', 'destino_id'], name='IMPUTACION_DESTINO_aa54ec_idx'),
        ),
        migrations.AddIndex(
            model_name='imputacion',
            index=models.Index(fields=['imp_fecha'], name='IMPUTACION_IMP_FEC_bf5c09_idx'),
        ),
    ]
