# Generated by Django 5.0.1 on 2026-02-14 00:18

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0014_cheque_fecha_acreditacion_alter_cheque_estado'),
        ('clientes', '0003_cliente_lista_precio_id'),
        ('cuenta_corriente', '0009_imputacion_alter_imputacioncompra_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('rec_id', models.AutoField(db_column='REC_ID', primary_key=True, serialize=False)),
                ('rec_fecha', models.DateField(db_column='REC_FECHA')),
                ('rec_numero', models.CharField(db_column='REC_NUMERO', help_text='Número de recibo (formato: 0001-00000001)', max_length=20, unique=True)),
                ('rec_total', models.DecimalField(db_column='REC_TOTAL', decimal_places=2, help_text='Monto total del recibo', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('rec_observacion', models.CharField(blank=True, db_column='REC_OBSERVACION', help_text='Observaciones del recibo', max_length=200, null=True)),
                ('rec_fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='REC_FECHA_CREACION')),
                ('rec_estado', models.CharField(choices=[('A', 'Activo'), ('N', 'Anulado')], db_column='REC_ESTADO', default='A', max_length=1)),
                ('rec_cliente', models.ForeignKey(db_column='REC_CLIENTE', help_text='Cliente que realiza el pago', on_delete=django.db.models.deletion.PROTECT, related_name='recibos', to='clientes.cliente')),
                ('rec_usuario', models.ForeignKey(db_column='REC_USUARIO', help_text='Usuario que registró el recibo', on_delete=django.db.models.deletion.PROTECT, related_name='recibos_creados', to=settings.AUTH_USER_MODEL)),
                ('sesion_caja', models.ForeignKey(blank=True, db_column='REC_SESION_CAJA', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recibos', to='caja.sesioncaja')),
            ],
            options={
                'verbose_name': 'Recibo',
                'verbose_name_plural': 'Recibos',
                'db_table': 'RECIBO',
                'indexes': [models.Index(fields=['rec_fecha'], name='RECIBO_REC_FEC_8ccf6f_idx'), models.Index(fields=['rec_cliente'], name='RECIBO_REC_CLI_08c610_idx'), models.Index(fields=['rec_estado'], name='RECIBO_REC_EST_2f0c06_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='recibo',
            constraint=models.CheckConstraint(check=models.Q(('rec_total__gt', 0)), name='rec_total_positivo'),
        ),
    ]
