# Generated by Django 5.0.1 on 2026-07-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta_corriente', '0010_recibo_recibo_rec_total_positivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='imputacion',
            name='imp_idempotency_key',
            field=models.CharField(blank=True, db_column='IMP_IDEMPOTENCY_KEY', max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='imputacion',
            constraint=models.UniqueConstraint(
                fields=('origen_content_type', 'origen_id', 'destino_content_type', 'destino_id', 'imp_idempotency_key'),
                name='imputacion_origen_destino_idempotency_unique',
            ),
        ),
    ]
