# Generated by Django 5.0.1 on 2025-05-26 03:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('color', models.CharField(default='#FFEB3B', max_length=7)),
                ('emoji', models.CharField(default='📝', max_length=10)),
            ],
            options={
                'ordering': ['-fecha_modificacion'],
            },
        ),
    ]
