# Generated by Django 5.0.1 on 2025-08-22 22:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_caducidad', models.DateTimeField(blank=True, null=True)),
                ('es_importante', models.BooleanField(default=False)),
                ('ultimo_acceso', models.DateTimeField(default=django.utils.timezone.now)),
                ('color', models.CharField(default='#FFEB3B', max_length=7)),
                ('emoji', models.CharField(default='📝', max_length=10)),
                ('estado', models.CharField(choices=[('AC', 'Activa'), ('AR', 'Archivada'), ('EL', 'Eliminada')], default='AC', help_text='Estado actual de la nota', max_length=2)),
                ('categoria', models.CharField(blank=True, help_text='Categoría de la nota', max_length=50, null=True)),
                ('etiquetas', models.TextField(blank=True, help_text='Lista de etiquetas separadas por coma', null=True)),
                ('metadata', models.TextField(blank=True, help_text='Campo genérico para almacenar metadatos en formato JSON', null=True)),
                ('numero', models.IntegerField(blank=True, help_text='Número secuencial para la nota', null=True)),
            ],
            options={
                'ordering': ['-ultimo_acceso'],
            },
        ),
    ]
