# Generated by Django 5.0.1 on 2025-05-26 15:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nota',
            options={'ordering': ['-ultimo_acceso']},
        ),
        migrations.AddField(
            model_name='nota',
            name='es_importante',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nota',
            name='fecha_caducidad',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nota',
            name='ultimo_acceso',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='nota',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
