# Generated by Django 5.0.1 on 2025-05-26 15:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0004_remove_nota_color_remove_nota_emoji_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nota',
            options={'ordering': ['-ultimo_acceso'], 'verbose_name': 'Nota', 'verbose_name_plural': 'Notas'},
        ),
        migrations.AddField(
            model_name='nota',
            name='categoria',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='nota',
            name='estado',
            field=models.CharField(choices=[('AC', 'Activa'), ('AR', 'Archivada'), ('EL', 'Eliminada')], default='AC', max_length=2),
        ),
        migrations.AddField(
            model_name='nota',
            name='etiquetas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nota',
            name='metadata',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nota',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='nota',
            index=models.Index(fields=['usuario', 'estado'], name='notas_nota_usuario_8f7d0c_idx'),
        ),
        migrations.AddIndex(
            model_name='nota',
            index=models.Index(fields=['usuario', 'es_importante'], name='notas_nota_usuario_ef69f0_idx'),
        ),
        migrations.AddIndex(
            model_name='nota',
            index=models.Index(fields=['usuario', 'categoria'], name='notas_nota_usuario_b4a6c7_idx'),
        ),
        migrations.AddIndex(
            model_name='nota',
            index=models.Index(fields=['usuario', 'fecha_caducidad'], name='notas_nota_usuario_b8c866_idx'),
        ),
    ]
