# Generated by Django 5.0.1 on 2025-06-18 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0006_alter_nota_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='categoria',
            field=models.CharField(blank=True, help_text='Categoría de la nota', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='nota',
            name='estado',
            field=models.CharField(choices=[('AC', 'Activa'), ('AR', 'Archivada'), ('EL', 'Eliminada')], default='AC', help_text='Estado actual de la nota', max_length=2),
        ),
        migrations.AddField(
            model_name='nota',
            name='etiquetas',
            field=models.TextField(blank=True, help_text='Lista de etiquetas separadas por coma', null=True),
        ),
        migrations.AddField(
            model_name='nota',
            name='metadata',
            field=models.TextField(blank=True, help_text='Campo genérico para almacenar metadatos en formato JSON', null=True),
        ),
        migrations.AddField(
            model_name='nota',
            name='numero',
            field=models.IntegerField(blank=True, help_text='Número secuencial para la nota', null=True),
        ),
    ]
