# Generated by Django 5.0.1 on 2025-05-20 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0011_alter_stockprove_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=15)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('timestamp_creacion', models.DateTimeField(auto_now_add=True)),
                ('timestamp_expiracion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('expirada', 'Expirada')], default='activa', max_length=10)),
                ('tipo_operacion', models.CharField(blank=True, max_length=20, null=True)),
                ('operacion_id', models.IntegerField(blank=True, null=True)),
                ('detalles', models.TextField(blank=True, null=True)),
                ('ferreteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.ferreteria')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.stock')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.proveedor')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reserva de Stock',
                'verbose_name_plural': 'Reservas de Stock',
            },
        ),
    ]
