# Generated by Django 5.0.1 on 2025-09-15 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=15)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('timestamp_creacion', models.DateTimeField(auto_now_add=True)),
                ('timestamp_expiracion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('expirada', 'Expirada')], default='activa', max_length=10)),
                ('tipo_operacion', models.CharField(blank=True, max_length=20, null=True)),
                ('operacion_id', models.IntegerField(blank=True, null=True)),
                ('detalles', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Reserva de Stock',
                'verbose_name_plural': 'Reservas de Stock',
            },
        ),
        migrations.CreateModel(
            name='FormLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('venta', 'Venta'), ('presupuesto', 'Presupuesto'), ('conversion', 'Conversión de Presupuesto')], max_length=20)),
                ('session_key', models.CharField(max_length=40)),
                ('timestamp_creacion', models.DateTimeField(auto_now_add=True)),
                ('timestamp_expiracion', models.DateTimeField()),
                ('presupuesto_id', models.IntegerField(blank=True, null=True)),
                ('ferreteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.ferreteria')),
            ],
            options={
                'verbose_name': 'Bloqueo de Formulario',
                'verbose_name_plural': 'Bloqueos de Formularios',
            },
        ),
    ]
