# Generated by Django 5.0.1 on 2025-09-15 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        ('reservas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='formlock',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservastock',
            name='ferreteria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.ferreteria'),
        ),
        migrations.AddField(
            model_name='reservastock',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.stock'),
        ),
        migrations.AddField(
            model_name='reservastock',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.proveedor'),
        ),
        migrations.AddField(
            model_name='reservastock',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='formlock',
            index=models.Index(fields=['tipo', 'presupuesto_id'], name='reservas_fo_tipo_e64064_idx'),
        ),
        migrations.AddIndex(
            model_name='formlock',
            index=models.Index(fields=['session_key'], name='reservas_fo_session_1eab1c_idx'),
        ),
    ]
