# Generated by Django 5.0.1 on 2025-05-20 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0011_alter_stockprove_unique_together'),
        ('reservas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('venta', 'Venta'), ('presupuesto', 'Presupuesto'), ('conversion', 'Conversión de Presupuesto')], max_length=20)),
                ('session_key', models.CharField(max_length=40)),
                ('timestamp_creacion', models.DateTimeField(auto_now_add=True)),
                ('timestamp_expiracion', models.DateTimeField()),
                ('presupuesto_id', models.IntegerField(blank=True, null=True)),
                ('ferreteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.ferreteria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bloqueo de Formulario',
                'verbose_name_plural': 'Bloqueos de Formularios',
                'indexes': [models.Index(fields=['tipo', 'presupuesto_id'], name='reservas_fo_tipo_e64064_idx'), models.Index(fields=['session_key'], name='reservas_fo_session_1eab1c_idx')],
            },
        ),
    ]
