"""Constantes compartidas de la app tenants."""

SLUG_MIN_LENGTH = 3
SLUG_MAX_LENGTH = 63
TRIAL_DIAS_DEFAULT = 14

SUBDOMINIOS_RESERVADOS = frozenset(
    {
        # Infraestructura
        "www",
        "api",
        "cdn",
        "static",
        "media",
        "assets",
        "mail",
        "smtp",
        "imap",
        "pop",
        "ftp",
        "ssh",
        "vpn",
        "dns",
        "ns1",
        "ns2",
        "mx",
        "proxy",
        # Autenticacion
        "login",
        "logout",
        "auth",
        "oauth",
        "sso",
        "register",
        "signup",
        "signin",
        "password",
        "reset",
        # Entornos
        "staging",
        "dev",
        "test",
        "demo",
        "sandbox",
        "beta",
        "alpha",
        "prod",
        "production",
        "qa",
        "uat",
        "preview",
        # Correo
        "email",
        "webmail",
        "postmaster",
        "abuse",
        "noreply",
        "mailer",
        # Soporte/corporativo
        "support",
        "help",
        "admin",
        "dashboard",
        "panel",
        "billing",
        "pay",
        "payment",
        "blog",
        "docs",
        "documentation",
        "status",
        "about",
        "terms",
        "privacy",
        "legal",
        "security",
        "contact",
        "careers",
        "press",
        "investor",
        "enterprise",
        "partner",
        # Producto
        "app",
        "desktop",
        "mobile",
        "download",
        "update",
        "store",
        "marketplace",
        "connect",
        "platform",
    }
)
