# Generated by Django 5.0.1 on 2025-05-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plazo',
            name='pla_pla1',
            field=models.SmallIntegerField(db_column='PLA_PLA1', default=0),
        ),
        migrations.AddField(
            model_name='plazo',
            name='pla_pla10',
            field=models.SmallIntegerField(db_column='PLA_PLA10', default=0),
        ),
        migrations.AddField(
            model_name='plazo',
            name='pla_pla11',
            field=models.SmallIntegerField(db_column='PLA_PLA11', default=0),
        ),
        migrations.AddField(
            model_name='plazo',
            name='pla_pla12',
            field=models.SmallIntegerField(db_column='PLA_PLA12', default=0),
        ),
        migrations.AddField(
            model_name='plazo',
            name='pla_pla2',
            field=models.SmallIntegerField(db_column='PLA_PLA2', default=0),
        ),
        migrations.AddField(
            model_name='plazo',
            name='pla_pla3',
            field=models.SmallIntegerField(db_column='PLA_PLA3', default=0),
        ),
        migrations.AddField(
            model_name='plazo',
            name='pla_pla4',
            field=models.SmallIntegerField(db_column='PLA_PLA4', default=0),
        ),
        migrations.AddField(
            model_name='plazo',
            name='pla_pla5',
            field=models.SmallIntegerField(db_column='PLA_PLA5', default=0),
        ),
        migrations.AddField(
            model_name='plazo',
            name='pla_pla6',
            field=models.SmallIntegerField(db_column='PLA_PLA6', default=0),
        ),
        migrations.AddField(
            model_name='plazo',
            name='pla_pla7',
            field=models.SmallIntegerField(db_column='PLA_PLA7', default=0),
        ),
        migrations.AddField(
            model_name='plazo',
            name='pla_pla8',
            field=models.SmallIntegerField(db_column='PLA_PLA8', default=0),
        ),
        migrations.AddField(
            model_name='plazo',
            name='pla_pla9',
            field=models.SmallIntegerField(db_column='PLA_PLA9', default=0),
        ),
        migrations.AddField(
            model_name='plazo',
            name='pla_por1',
            field=models.DecimalField(db_column='PLA_POR1', decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='plazo',
            name='pla_por10',
            field=models.DecimalField(db_column='PLA_POR10', decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='plazo',
            name='pla_por11',
            field=models.DecimalField(db_column='PLA_POR11', decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='plazo',
            name='pla_por12',
            field=models.DecimalField(db_column='PLA_POR12', decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='plazo',
            name='pla_por2',
            field=models.DecimalField(db_column='PLA_POR2', decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='plazo',
            name='pla_por3',
            field=models.DecimalField(db_column='PLA_POR3', decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='plazo',
            name='pla_por4',
            field=models.DecimalField(db_column='PLA_POR4', decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='plazo',
            name='pla_por5',
            field=models.DecimalField(db_column='PLA_POR5', decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='plazo',
            name='pla_por6',
            field=models.DecimalField(db_column='PLA_POR6', decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='plazo',
            name='pla_por7',
            field=models.DecimalField(db_column='PLA_POR7', decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='plazo',
            name='pla_por8',
            field=models.DecimalField(db_column='PLA_POR8', decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='plazo',
            name='pla_por9',
            field=models.DecimalField(db_column='PLA_POR9', decimal_places=2, default=0, max_digits=4),
        ),
    ]
