# Generated by Django 5.0.1 on 2025-09-07 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_datos_iniciales_clientes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['activo'], name='CLIENTES_CLI_ACT_aecb6d_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['cuit'], name='CLIENTES_CLI_CUI_1e9e21_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['razon'], name='CLIENTES_CLI_RAZ_0c3e6f_idx'),
        ),
    ]
