# Generated by Django 5.0.1 on 2026-01-28 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_datos_iniciales_clientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='lista_precio_id',
            field=models.IntegerField(blank=True, db_column='NUMERO_LISTA_DE_PRECIOS_ASIGNADA', default=0, help_text='Número de lista de precios asignada (0=Minorista, 1-4=Otras listas)', null=True),
        ),
    ]
