# Generated by Django 5.0.1 on 2025-08-18 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_datos_iniciales_clientes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='codigo',
        ),
    ]
