# Generated by Django 5.0.1 on 2025-08-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_plazo_activo_alter_plazo_pla_por1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecsalcta',
            field=models.DateField(blank=True, db_column='CLI_FECSALCTA', null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='impsalcta',
            field=models.DecimalField(blank=True, db_column='CLI_IMPSALCTA', decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='lineacred',
            field=models.IntegerField(blank=True, db_column='CLI_LINEACRED', null=True),
        ),
    ]
