# Generated by Django 5.0.1 on 2025-08-18 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_remove_cliente_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='zona',
            field=models.CharField(blank=True, db_column='CLI_ZONA', max_length=10, null=True),
        ),
    ]
