# Generated by Django 5.0.1 on 2025-09-07 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_clientes_cli_act_aecb6d_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cliente',
            name='CLIENTES_CLI_ACT_aecb6d_idx',
        ),
        migrations.RemoveIndex(
            model_name='cliente',
            name='CLIENTES_CLI_CUI_1e9e21_idx',
        ),
        migrations.RemoveIndex(
            model_name='cliente',
            name='CLIENTES_CLI_RAZ_0c3e6f_idx',
        ),
    ]
