# Generated by Django 5.0.1 on 2025-08-07 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_cliente_fecsalcta_alter_cliente_impsalcta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cuit',
            field=models.CharField(blank=True, db_column='CLI_CUIT', max_length=11, null=True, unique=True),
        ),
    ]
