# Generated by Django 5.0.1 on 2025-05-14 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cbt_facturaa', models.IntegerField(db_column='CBT_FACTURAA')),
                ('cbt_facturab', models.IntegerField(db_column='CBT_FACTURAB')),
                ('cbt_remito', models.IntegerField(db_column='CBT_REMITO')),
                ('cbt_pedidovta', models.IntegerField(db_column='CBT_PEDIDOVTA')),
                ('cbt_presupuesto', models.IntegerField(db_column='CBT_PRESUPUESTO')),
                ('cbt_pedidocpr', models.IntegerField(db_column='CBT_PEDIDOCPR')),
                ('cbt_bloqueo', models.CharField(db_column='CBT_BLOQUEO', max_length=30)),
                ('cbt_puntovta', models.IntegerField(db_column='CBT_PUNTOVTA')),
                ('cbt_ordenpago', models.IntegerField(db_column='CBT_ORDENPAGO')),
                ('cbt_creditoa', models.IntegerField(db_column='CBT_CREDITOA', null=True)),
                ('cbt_creditob', models.IntegerField(db_column='CBT_CREDITOB', null=True)),
                ('cbt_debitoa', models.IntegerField(db_column='CBT_DEBITOA', null=True)),
                ('cbt_debitob', models.IntegerField(db_column='CBT_DEBITOB', null=True)),
                ('cbt_puntovtafe', models.IntegerField(db_column='CBT_PUNTOVTAFE', null=True)),
                ('cbt_facturam', models.IntegerField(db_column='CBT_FACTURAM')),
                ('cbt_creditom', models.IntegerField(db_column='CBT_CREDITOM')),
                ('cbt_debitom', models.IntegerField(db_column='CBT_DEBITOM')),
            ],
            options={
                'db_table': 'COMPROBANTES',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('ven_id', models.AutoField(db_column='VEN_ID', primary_key=True, serialize=False)),
                ('ven_sucursal', models.SmallIntegerField(db_column='VEN_SUCURSAL')),
                ('ven_fecha', models.DateField(db_column='VEN_FECHA')),
                ('ven_codcomprob', models.SmallIntegerField(db_column='VEN_CODCOMPROB', null=True)),
                ('ven_punto', models.SmallIntegerField(db_column='VEN_PUNTO')),
                ('ven_numero', models.IntegerField(db_column='VEN_NUMERO')),
                ('ven_impneto', models.DecimalField(db_column='VEN_IMPNETO', decimal_places=2, max_digits=15)),
                ('ven_descu1', models.DecimalField(db_column='VEN_DESCU1', decimal_places=2, max_digits=4)),
                ('ven_descu2', models.DecimalField(db_column='VEN_DESCU2', decimal_places=2, max_digits=4)),
                ('ven_descu3', models.DecimalField(db_column='VEN_DESCU3', decimal_places=2, max_digits=4)),
                ('ven_total', models.BigIntegerField(db_column='VEN_TOTAL', null=True)),
                ('ven_vdocomvta', models.DecimalField(db_column='VEN_VDOCOMVTA', decimal_places=2, max_digits=4)),
                ('ven_vdocomcob', models.DecimalField(db_column='VEN_VDOCOMCOB', decimal_places=2, max_digits=4)),
                ('ven_estado', models.CharField(db_column='VEN_ESTADO', max_length=2, null=True)),
                ('ven_idcli', models.IntegerField(db_column='VEN_IDCLI')),
                ('ven_idpla', models.IntegerField(db_column='VEN_IDPLA')),
                ('ven_idvdo', models.IntegerField(db_column='VEN_IDVDO')),
                ('ven_copia', models.SmallIntegerField(db_column='VEN_COPIA')),
                ('ven_fecanula', models.DateField(db_column='VEN_FECANULA', null=True)),
                ('ven_cae', models.CharField(db_column='VEN_CAE', max_length=20)),
                ('ven_caevencimiento', models.DateField(db_column='VEN_CAEVENCIMIENTO', null=True)),
                ('ven_qr', models.BinaryField(db_column='VEN_QR', null=True)),
            ],
            options={
                'db_table': 'VENTA',
            },
        ),
        migrations.CreateModel(
            name='VentaDetalleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vdi_idve', models.IntegerField(db_column='VDI_IDVE')),
                ('vdi_orden', models.SmallIntegerField(db_column='VDI_ORDEN')),
                ('vdi_idsto', models.IntegerField(db_column='VDI_IDSTO')),
                ('vdi_cantidad', models.DecimalField(db_column='VDI_CANTIDAD', decimal_places=2, max_digits=9)),
                ('vdi_importe', models.DecimalField(db_column='VDI_IMPORTE', decimal_places=3, max_digits=13)),
                ('vdi_bonifica', models.DecimalField(db_column='VDI_BONIFICA', decimal_places=2, max_digits=4)),
                ('vdi_detalle1', models.CharField(db_column='VDI_DETALLE1', max_length=40, null=True)),
                ('vdi_detalle2', models.CharField(db_column='VDI_DETALLE2', max_length=40, null=True)),
                ('vdi_idaliiva', models.IntegerField(db_column='VDI_IDALIIVA')),
            ],
            options={
                'db_table': 'VENTA_DETAITEM',
            },
        ),
        migrations.CreateModel(
            name='VentaDetalleMan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vdm_idve', models.IntegerField(db_column='VDM_IDVE')),
                ('vdm_orden', models.SmallIntegerField(db_column='VDM_ORDEN')),
                ('vdm_deno', models.CharField(db_column='VDM_DENO', max_length=40)),
                ('vdm_importe', models.DecimalField(db_column='VDM_IMPORTE', decimal_places=2, max_digits=12)),
                ('vdm_exento', models.CharField(db_column='VDM_EXENTO', max_length=1, null=True)),
            ],
            options={
                'db_table': 'VENTA_DETAMAN',
            },
        ),
        migrations.CreateModel(
            name='VentaRemPed',
            fields=[
                ('vrp_id', models.AutoField(db_column='VRP_ID', primary_key=True, serialize=False)),
                ('vrp_sucursal', models.SmallIntegerField(db_column='VRP_SUCURSAL')),
                ('vrp_orden', models.SmallIntegerField(db_column='VRP_ORDEN')),
                ('vrp_fecha', models.DateField(db_column='VRP_FECHA')),
                ('vrp_tipo', models.CharField(db_column='VRP_TIPO', max_length=2)),
                ('vrp_letra', models.CharField(db_column='VRP_LETRA', max_length=1)),
                ('vrp_punto', models.SmallIntegerField(db_column='VRP_PUNTO')),
                ('vrp_idcli', models.IntegerField(db_column='VRP_IDCLI')),
                ('vrp_numero', models.IntegerField(db_column='VRP_NUMERO')),
                ('vrp_idsto', models.IntegerField(db_column='VRP_IDSTO')),
                ('vrp_deno', models.CharField(db_column='VRP_DENO', max_length=40, null=True)),
                ('vrp_cantidad', models.DecimalField(db_column='VRP_CANTIDAD', decimal_places=2, max_digits=9)),
                ('vrp_importe', models.DecimalField(db_column='VRP_IMPORTE', decimal_places=2, max_digits=12)),
                ('vrp_cantiusa', models.DecimalField(db_column='VRP_CANTIUSA', decimal_places=2, max_digits=9)),
                ('vrp_bonifica', models.DecimalField(db_column='VRP_BONIFICA', decimal_places=2, max_digits=4, null=True)),
                ('vrp_pretot', models.BigIntegerField(db_column='VRP_PRETOT', null=True)),
                ('vrp_ref', models.CharField(db_column='VRP_REF', max_length=50, null=True)),
                ('vrp_presenta', models.CharField(db_column='VRP_PRESENTA', max_length=25, null=True)),
                ('vrp_cortado', models.CharField(db_column='VRP_CORTADO', max_length=5, null=True)),
                ('vrp_piezas', models.SmallIntegerField(db_column='VRP_PIEZAS', null=True)),
            ],
            options={
                'db_table': 'VENTA_REMPED',
            },
        ),
    ]
