# Generated by Django 5.0.1 on 2025-05-17 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventadetalleitem',
            name='vdi_idpro',
            field=models.IntegerField(db_column='VDI_IDPRO', null=True),
        ),
    ]
