# Generated by Django 5.0.1 on 2025-05-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_ventadetalleitem_vdi_idpro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='ven_cae',
            field=models.CharField(blank=True, db_column='VEN_CAE', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='ven_caevencimiento',
            field=models.DateField(blank=True, db_column='VEN_CAEVENCIMIENTO', null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='ven_codcomprob',
            field=models.SmallIntegerField(blank=True, db_column='VEN_CODCOMPROB', null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='ven_estado',
            field=models.CharField(blank=True, db_column='VEN_ESTADO', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='ven_fecanula',
            field=models.DateField(blank=True, db_column='VEN_FECANULA', null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='ven_qr',
            field=models.BinaryField(blank=True, db_column='VEN_QR', null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='ven_total',
            field=models.BigIntegerField(blank=True, db_column='VEN_TOTAL', null=True),
        ),
    ]
