# Generated by Django 5.0.1 on 2026-02-03 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
        ('ventas', '0003_nuevas_vistas'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='sesion_caja',
            field=models.ForeignKey(blank=True, db_column='VEN_SESION_CAJA_ID', help_text='Sesión de caja en la que se registró esta venta', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='caja.sesioncaja'),
        ),
    ]
