# Generated by Django 5.0.1 on 2025-05-21 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_alter_venta_ven_cae_alter_venta_ven_caevencimiento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comprobante',
            options={'verbose_name': 'Comprobante', 'verbose_name_plural': 'Comprobantes'},
        ),
        migrations.RemoveField(
            model_name='comprobante',
            name='cbt_bloqueo',
        ),
        migrations.RemoveField(
            model_name='comprobante',
            name='cbt_creditoa',
        ),
        migrations.RemoveField(
            model_name='comprobante',
            name='cbt_creditob',
        ),
        migrations.RemoveField(
            model_name='comprobante',
            name='cbt_creditom',
        ),
        migrations.RemoveField(
            model_name='comprobante',
            name='cbt_debitoa',
        ),
        migrations.RemoveField(
            model_name='comprobante',
            name='cbt_debitob',
        ),
        migrations.RemoveField(
            model_name='comprobante',
            name='cbt_debitom',
        ),
        migrations.RemoveField(
            model_name='comprobante',
            name='cbt_facturaa',
        ),
        migrations.RemoveField(
            model_name='comprobante',
            name='cbt_facturab',
        ),
        migrations.RemoveField(
            model_name='comprobante',
            name='cbt_facturam',
        ),
        migrations.RemoveField(
            model_name='comprobante',
            name='cbt_ordenpago',
        ),
        migrations.RemoveField(
            model_name='comprobante',
            name='cbt_pedidocpr',
        ),
        migrations.RemoveField(
            model_name='comprobante',
            name='cbt_pedidovta',
        ),
        migrations.RemoveField(
            model_name='comprobante',
            name='cbt_presupuesto',
        ),
        migrations.RemoveField(
            model_name='comprobante',
            name='cbt_puntovta',
        ),
        migrations.RemoveField(
            model_name='comprobante',
            name='cbt_puntovtafe',
        ),
        migrations.RemoveField(
            model_name='comprobante',
            name='cbt_remito',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='ven_codcomprob',
        ),
        migrations.AddField(
            model_name='comprobante',
            name='activo',
            field=models.BooleanField(db_column='CBT_ACTIVO', default=True),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='codigo_afip',
            field=models.CharField(blank=True, db_column='CBT_CODIGO_AFIP', max_length=8, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='descripcion',
            field=models.CharField(blank=True, db_column='CBT_DESCRIPCION', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='letra',
            field=models.CharField(blank=True, db_column='CBT_LETRA', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='nombre',
            field=models.CharField(blank=True, db_column='CBT_NOMBRE', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='tipo',
            field=models.CharField(blank=True, db_column='CBT_TIPO', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='comprobante',
            field=models.ForeignKey(blank=True, db_column='VEN_CODCOMPROB', null=True, on_delete=django.db.models.deletion.PROTECT, to='ventas.comprobante'),
        ),
    ]
