# Generated by Django 5.0.1 on 2025-05-21 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_alter_comprobante_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobante',
            name='codigo_afip',
            field=models.CharField(db_column='CBT_CODIGO_AFIP', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='nombre',
            field=models.CharField(db_column='CBT_NOMBRE', max_length=50),
        ),
    ]
