# Generated by Django 5.0.1 on 2025-09-07 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_clientes_cli_act_aecb6d_idx_and_more'),
        ('ventas', '0004_agregar_comprobante_orden_compra'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['ven_fecha'], name='VENTA_VEN_FEC_72076a_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['ven_estado'], name='VENTA_VEN_EST_5e537a_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['ven_idcli'], name='VENTA_VEN_IDC_cc0484_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['ven_fecha', 'ven_estado'], name='VENTA_VEN_FEC_b8be95_idx'),
        ),
        migrations.AddIndex(
            model_name='ventadetalleitem',
            index=models.Index(fields=['vdi_idve', 'vdi_orden'], name='VENTA_DETAI_VDI_IDV_ff9bd6_idx'),
        ),
    ]
