# Generated by Django 5.0.1 on 2025-05-21 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_alter_comprobante_codigo_afip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventadetalleitem',
            name='vdi_idve',
            field=models.ForeignKey(db_column='VDI_IDVE', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ventas.venta'),
        ),
        migrations.AlterUniqueTogether(
            name='venta',
            unique_together={('ven_punto', 'ven_numero', 'comprobante')},
        ),
        migrations.AddConstraint(
            model_name='venta',
            constraint=models.CheckConstraint(check=models.Q(('ven_numero__gt', 0)), name='ven_numero_positivo'),
        ),
        migrations.AddConstraint(
            model_name='venta',
            constraint=models.CheckConstraint(check=models.Q(('ven_punto__gt', 0)), name='ven_punto_positivo'),
        ),
    ]
