# Generated by Django 5.0.1 on 2025-05-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_alter_ventadetalleitem_vdi_idve_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='iva_desglose',
            field=models.JSONField(blank=True, db_column='VEN_IVA_DESGLOSE', null=True),
        ),
    ]
