# Generated by Django 5.0.1 on 2026-02-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_conversion_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='venta',
            name='venta_convertida_idx',
        ),
        migrations.AlterField(
            model_name='venta',
            name='ven_descuento_cierre',
            field=models.DecimalField(db_column='VEN_DESCUENTO_CIERRE', decimal_places=2, default=0, help_text='Descuento de cierre/redondeo en monto fijo', max_digits=15),
        ),
    ]
