# Generated by Django 5.0.1 on 2025-05-23 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_venta_iva_desglose'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='ven_bonificacion_general',
            field=models.FloatField(db_column='VEN_BONIFICACION_GENERAL', default=0.0),
        ),
    ]
