# Generated by Django 5.0.1 on 2025-05-23 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_venta_ven_bonificacion_general'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='ven_total',
            field=models.DecimalField(blank=True, db_column='VEN_TOTAL', decimal_places=2, max_digits=15, null=True),
        ),
    ]
