# Generated by Django 5.0.1 on 2025-05-30 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0009_alter_venta_ven_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='comprobante',
            field=models.ForeignKey(blank=True, db_column='VEN_CODCOMPROB', null=True, on_delete=django.db.models.deletion.PROTECT, to='ventas.comprobante', to_field='codigo_afip'),
        ),
    ]
