# Generated by Django 5.0.1 on 2025-06-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0010_alter_venta_comprobante'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventadetalleitem',
            name='vdi_costo',
            field=models.DecimalField(db_column='VDI_COSTO', decimal_places=3, default=30, max_digits=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ventadetalleitem',
            name='vdi_margen',
            field=models.DecimalField(db_column='VDI_MARGEN', decimal_places=2, default=30, max_digits=4),
            preserve_default=False,
        ),
    ]
