# Generated by Django 5.0.1 on 2026-02-24 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_lista_precio_id'),
        ('productos', '0014_drop_vistas_Stock'),
        ('ventas', '0011_drop_vistas_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='ven_idpla',
            field=models.ForeignKey(db_column='VEN_IDPLA', on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='clientes.plazo'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='ven_idvdo',
            field=models.ForeignKey(db_column='VEN_IDVDO', on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='clientes.vendedor'),
        ),
        migrations.AlterField(
            model_name='ventadetalleitem',
            name='vdi_idaliiva',
            field=models.ForeignKey(db_column='VDI_IDALIIVA', on_delete=django.db.models.deletion.PROTECT, related_name='ventas_detalles', to='productos.alicuotaiva'),
        ),
        migrations.AlterField(
            model_name='ventadetalleitem',
            name='vdi_idpro',
            field=models.ForeignKey(blank=True, db_column='VDI_IDPRO', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas_detalles', to='productos.proveedor'),
        ),
        migrations.AlterField(
            model_name='ventadetalleitem',
            name='vdi_idsto',
            field=models.ForeignKey(blank=True, db_column='VDI_IDSTO', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas_detalles', to='productos.stock'),
        ),
    ]
