# Generated by Django 5.0.1 on 2025-06-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0011_ventadetalleitem_vdi_costo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='hora_creacion',
            field=models.TimeField(auto_now_add=True, db_column='VEN_HORA_CREACION', null=True),
        ),
    ]
