# Generated by Django 5.0.1 on 2025-06-10 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0012_venta_hora_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='ven_cuit',
            field=models.CharField(blank=True, db_column='VEN_CUIT', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='ven_domicilio',
            field=models.CharField(blank=True, db_column='VEN_DOMICILIO', max_length=100, null=True),
        ),
    ]
