# Generated by Django 5.0.1 on 2026-03-06 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0012_alter_venta_ven_idpla_alter_venta_ven_idvdo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='ven_idlpa',
            field=models.SmallIntegerField(db_column='VEN_IDLPA', default=0, help_text='Número de lista de precios activa al momento de crear la venta/presupuesto'),
        ),
    ]
