# Generated by Django 5.0.1 on 2026-06-18 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0017_add_fondos_propios'),
        ('clientes', '0003_cliente_lista_precio_id'),
        ('productos', '0018_stockprove_proveedor_codigo_idx'),
        ('ventas', '0013_venta_ven_idlpa'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['ven_fecha', 'comprobante', 'ven_estado'], name='VENTA_VEN_FEC_4b8c97_idx'),
        ),
        migrations.AddIndex(
            model_name='ventadetalleitem',
            index=models.Index(fields=['vdi_idsto'], name='VENTA_DETAI_VDI_IDS_a4a0e2_idx'),
        ),
    ]
