# Generated by Django 5.0.1 on 2025-06-11 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0014_vista_ventadetalleitem_calculado'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentaCalculada',
            fields=[
                ('ven_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ven_sucursal', models.SmallIntegerField()),
                ('ven_fecha', models.DateField()),
                ('ven_punto', models.SmallIntegerField()),
                ('ven_numero', models.IntegerField()),
                ('ven_descu1', models.DecimalField(decimal_places=2, max_digits=4)),
                ('ven_descu2', models.DecimalField(decimal_places=2, max_digits=4)),
                ('subtotal_bruto', models.DecimalField(decimal_places=3, max_digits=15)),
                ('ven_impneto', models.DecimalField(decimal_places=3, max_digits=15)),
                ('iva_global', models.DecimalField(decimal_places=3, max_digits=15)),
                ('ven_total', models.DecimalField(decimal_places=3, max_digits=15)),
                ('iva_desglose', models.JSONField()),
            ],
            options={
                'db_table': 'VENTA_CALCULADO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VentaDetalleItemCalculado',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vdi_idve', models.IntegerField()),
                ('vdi_orden', models.SmallIntegerField()),
                ('vdi_idsto', models.IntegerField()),
                ('vdi_idpro', models.IntegerField()),
                ('vdi_cantidad', models.DecimalField(decimal_places=2, max_digits=9)),
                ('vdi_costo', models.DecimalField(decimal_places=3, max_digits=13)),
                ('vdi_margen', models.DecimalField(decimal_places=2, max_digits=4)),
                ('vdi_bonifica', models.DecimalField(decimal_places=2, max_digits=4)),
                ('vdi_idaliiva', models.IntegerField()),
                ('vdi_importe', models.DecimalField(decimal_places=3, max_digits=13)),
                ('vdi_importe_total', models.DecimalField(decimal_places=3, max_digits=15)),
                ('vdi_ivaitem', models.DecimalField(decimal_places=3, max_digits=15)),
            ],
            options={
                'db_table': 'VENTADETALLEITEM_CALCULADO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VentaIVAAlicuota',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('vdi_idve', models.IntegerField()),
                ('vdi_idaliiva', models.IntegerField()),
                ('iva_total', models.DecimalField(decimal_places=3, max_digits=15)),
            ],
            options={
                'db_table': 'VENTAIVA_ALICUOTA',
                'managed': False,
            },
        ),
    ]
