# Generated by Django 5.0.1 on 2026-06-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0014_venta_venta_ven_fec_4b8c97_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='iva_guardado',
            field=models.DecimalField(db_column='VEN_IVA_GUARDADO', decimal_places=2, default=0, help_text='IVA total. Se actualiza via signals al cambiar ítems.', max_digits=15),
        ),
        migrations.AddField(
            model_name='venta',
            name='neto_guardado',
            field=models.DecimalField(db_column='VEN_NETO_GUARDADO', decimal_places=2, default=0, help_text='Importe neto gravado. Se actualiza via signals al cambiar ítems.', max_digits=15),
        ),
        migrations.AddField(
            model_name='venta',
            name='subtotal_bruto_guardado',
            field=models.DecimalField(db_column='VEN_SUBTOTAL_BRUTO_GUARDADO', decimal_places=2, default=0, help_text='Subtotal bruto antes de descuentos. Se actualiza via signals al cambiar ítems.', max_digits=15),
        ),
        migrations.AddField(
            model_name='venta',
            name='total_guardado',
            field=models.DecimalField(db_column='VEN_TOTAL_GUARDADO', decimal_places=2, default=0, help_text='Total final. Se actualiza via signals al cambiar ítems.', max_digits=15),
        ),
    ]
