# Generated by Django 5.0.1 on 2026-07-09 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0020_stock_stock_deno_trgm_idx'),
        ('ventas', '0015_venta_iva_guardado_venta_neto_guardado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostventaOperacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('operacion_uid', models.UUIDField(db_index=True, unique=True)),
                ('tipo', models.CharField(choices=[('DEVOLUCION', 'Devolucion'), ('CAMBIO', 'Cambio')], max_length=20)),
                ('resolucion_dinero', models.CharField(max_length=30)),
                ('motivo', models.TextField()),
                ('motivo_forzado', models.TextField(blank=True, default='')),
                ('total_credito', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_debito', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('payload_hash', models.CharField(max_length=64)),
                ('estado', models.CharField(choices=[('INICIADA', 'Iniciada'), ('COMPLETADA', 'Completada')], default='INICIADA', max_length=20)),
                ('payload_snapshot', models.JSONField(default=dict)),
                ('resultado_snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nota_credito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='postventas_nc', to='ventas.venta')),
                ('nueva_venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='postventas_nueva_venta', to='ventas.venta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('venta_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postventas_origen', to='ventas.venta')),
            ],
            options={
                'db_table': 'VENTA_POSTVENTA_OPERACION',
            },
        ),
        migrations.CreateModel(
            name='PostventaOperacionItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(choices=[('DEVUELTO', 'Devuelto'), ('NUEVO', 'Nuevo')], max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=15)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('detalle', models.CharField(blank=True, default='', max_length=200)),
                ('operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ventas.postventaoperacion')),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='productos.stock')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='productos.proveedor')),
                ('venta_detalle_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ventas.ventadetalleitem')),
            ],
            options={
                'db_table': 'VENTA_POSTVENTA_OPERACION_ITEM',
            },
        ),
        migrations.AddIndex(
            model_name='postventaoperacion',
            index=models.Index(fields=['venta_origen', 'tipo'], name='VENTA_POSTV_venta_o_b614d8_idx'),
        ),
        migrations.AddIndex(
            model_name='postventaoperacion',
            index=models.Index(fields=['created_at'], name='VENTA_POSTV_created_06724c_idx'),
        ),
        migrations.AddIndex(
            model_name='postventaoperacionitem',
            index=models.Index(fields=['venta_detalle_origen', 'rol'], name='VENTA_POSTV_venta_d_dbcd0d_idx'),
        ),
        migrations.AddIndex(
            model_name='postventaoperacionitem',
            index=models.Index(fields=['operacion', 'rol'], name='VENTA_POSTV_operaci_4a9cf6_idx'),
        ),
    ]
