# Generated by Django 5.0.1 on 2025-06-11 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0016_vistas_ventaiva_alicuota_y_ventacalculado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='iva_desglose',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='ven_impneto',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='ven_total',
        ),
        migrations.RemoveField(
            model_name='ventadetalleitem',
            name='vdi_importe',
        ),
    ]
