# Generated by Django 5.0.1 on 2025-06-15 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0023_refinar_vistas_calculos_frontend'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            -- PASO 1: Eliminar la vista VENTA_CALCULADO existente para poder redefinirla.
            DROP VIEW IF EXISTS "VENTA_CALCULADO";

            -- PASO 2: Recrear la vista VENTA_CALCULADO con la lógica de cálculo de IVA y Total corregida.
            CREATE VIEW "VENTA_CALCULADO" AS
            WITH SubtotalesPorVenta AS (
                SELECT
                    vdi_idve,
                    SUM(vdi_importe_total) as subtotal_bruto
                FROM "VENTADETALLEITEM_CALCULADO"
                GROUP BY vdi_idve
            ),
            IVAPorVenta AS (
                SELECT
                    vdi_idve,
                    SUM(iva) as iva_global -- Nota: Este 'iva_global' es sobre el bruto.
                FROM "VENTADETALLEITEM_CALCULADO"
                GROUP BY vdi_idve
            )
            SELECT
                v."VEN_ID" AS ven_id,
                v."VEN_SUCURSAL" AS ven_sucursal,
                v."VEN_FECHA" AS ven_fecha,
                v."VEN_HORA_CREACION" AS hora_creacion,
                v."VEN_CODCOMPROB" AS comprobante_id,
                c."CBT_NOMBRE" AS comprobante_nombre,
                c."CBT_LETRA" AS comprobante_letra,
                c."CBT_TIPO" AS comprobante_tipo,
                c."CBT_CODIGO_AFIP" AS comprobante_codigo_afip,
                c."CBT_DESCRIPCION" AS comprobante_descripcion,
                c."CBT_ACTIVO" AS comprobante_activo,
                v."VEN_PUNTO" AS ven_punto,
                v."VEN_NUMERO" AS ven_numero,
                v."VEN_DESCU1" AS ven_descu1,
                v."VEN_DESCU2" AS ven_descu2,
                v."VEN_DESCU3" AS ven_descu3,
                v."VEN_VDOCOMVTA" AS ven_vdocomvta,
                v."VEN_VDOCOMCOB" AS ven_vdocomcob,
                v."VEN_ESTADO" AS ven_estado,
                v."VEN_IDCLI" AS ven_idcli,
                v."VEN_CUIT" AS ven_cuit,
                v."VEN_DOMICILIO" AS ven_domicilio,
                v."VEN_IDPLA" AS ven_idpla,
                v."VEN_IDVDO" AS ven_idvdo,
                v."VEN_COPIA" AS ven_copia,
                v."VEN_FECANULA" AS ven_fecanula,
                v."VEN_CAE" AS ven_cae,
                v."VEN_CAEVENCIMIENTO" AS ven_caevencimiento,
                v."VEN_QR" AS ven_qr,
                v."VEN_BONIFICACION_GENERAL" AS ven_bonificacion_general,
                ROUND(st.subtotal_bruto, 2) AS subtotal_bruto,
                -- El neto gravado se calcula correctamente.
                ROUND(st.subtotal_bruto * (1 - v."VEN_DESCU1" / 100.0) * (1 - v."VEN_DESCU2" / 100.0), 2) AS ven_impneto,
                -- CORREGIDO: El IVA global también se ve afectado por los descuentos generales.
                ROUND(COALESCE(iv.iva_global, 0) * (1 - v."VEN_DESCU1" / 100.0) * (1 - v."VEN_DESCU2" / 100.0), 2) AS iva_global,
                -- CORREGIDO: Se suma el subtotal y el iva bruto, y A ESE TOTAL se le aplican los descuentos.
                ROUND((st.subtotal_bruto + COALESCE(iv.iva_global, 0)) * (1 - v."VEN_DESCU1" / 100.0) * (1 - v."VEN_DESCU2" / 100.0), 2) AS ven_total
            FROM
                "VENTA" v
                JOIN SubtotalesPorVenta st ON st.vdi_idve = v."VEN_ID"
                LEFT JOIN IVAPorVenta iv ON iv.vdi_idve = v."VEN_ID"
                LEFT JOIN "COMPROBANTES" c ON v."VEN_CODCOMPROB" = c."CBT_CODIGO_AFIP";
            """,
            reverse_sql="""
            -- Para revertir, se restaura la vista VENTA_CALCULADO a su estado anterior (el de la migración 0023).
            DROP VIEW IF EXISTS "VENTA_CALCULADO";
            CREATE VIEW "VENTA_CALCULADO" AS
            WITH SubtotalesPorVenta AS (
                SELECT
                    vdi_idve,
                    SUM(vdi_importe_total) as subtotal_bruto
                FROM "VENTADETALLEITEM_CALCULADO"
                GROUP BY vdi_idve
            ),
            IVAPorVenta AS (
                SELECT
                    vdi_idve,
                    SUM(iva) as iva_global
                FROM "VENTADETALLEITEM_CALCULADO"
                GROUP BY vdi_idve
            )
            SELECT
                v."VEN_ID" AS ven_id,
                v."VEN_SUCURSAL" AS ven_sucursal,
                v."VEN_FECHA" AS ven_fecha,
                v."VEN_HORA_CREACION" AS hora_creacion,
                v."VEN_CODCOMPROB" AS comprobante_id,
                c."CBT_NOMBRE" AS comprobante_nombre,
                c."CBT_LETRA" AS comprobante_letra,
                c."CBT_TIPO" AS comprobante_tipo,
                c."CBT_CODIGO_AFIP" AS comprobante_codigo_afip,
                c."CBT_DESCRIPCION" AS comprobante_descripcion,
                c."CBT_ACTIVO" AS comprobante_activo,
                v."VEN_PUNTO" AS ven_punto,
                v."VEN_NUMERO" AS ven_numero,
                v."VEN_DESCU1" AS ven_descu1,
                v."VEN_DESCU2" AS ven_descu2,
                v."VEN_DESCU3" AS ven_descu3,
                v."VEN_VDOCOMVTA" AS ven_vdocomvta,
                v."VEN_VDOCOMCOB" AS ven_vdocomcob,
                v."VEN_ESTADO" AS ven_estado,
                v."VEN_IDCLI" AS ven_idcli,
                v."VEN_CUIT" AS ven_cuit,
                v."VEN_DOMICILIO" AS ven_domicilio,
                v."VEN_IDPLA" AS ven_idpla,
                v."VEN_IDVDO" AS ven_idvdo,
                v."VEN_COPIA" AS ven_copia,
                v."VEN_FECANULA" AS ven_fecanula,
                v."VEN_CAE" AS ven_cae,
                v."VEN_CAEVENCIMIENTO" AS ven_caevencimiento,
                v."VEN_QR" AS ven_qr,
                v."VEN_BONIFICACION_GENERAL" AS ven_bonificacion_general,
                ROUND(st.subtotal_bruto, 2) AS subtotal_bruto,
                ROUND(st.subtotal_bruto * (1 - v."VEN_DESCU1" / 100.0) * (1 - v."VEN_DESCU2" / 100.0), 2) AS ven_impneto,
                ROUND(COALESCE(iv.iva_global, 0), 2) AS iva_global,
                ROUND((st.subtotal_bruto * (1 - v."VEN_DESCU1" / 100.0) * (1 - v."VEN_DESCU2" / 100.0)) + COALESCE(iv.iva_global, 0), 2) AS ven_total
            FROM
                "VENTA" v
                JOIN SubtotalesPorVenta st ON st.vdi_idve = v."VEN_ID"
                LEFT JOIN IVAPorVenta iv ON iv.vdi_idve = v."VEN_ID"
                LEFT JOIN "COMPROBANTES" c ON v."VEN_CODCOMPROB" = c."CBT_CODIGO_AFIP";
            """
        ),
    ] 