# Generated by Django 5.0.1 on 2025-06-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0028_drop_vistas_para_alterar_detalleitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventadetalleitem',
            name='vdi_idpro',
            field=models.IntegerField(blank=True, db_column='VDI_IDPRO', null=True),
        ),
        migrations.AlterField(
            model_name='ventadetalleitem',
            name='vdi_idsto',
            field=models.IntegerField(blank=True, db_column='VDI_IDSTO', null=True),
        ),
    ]
