# Generated by Django 5.0.6 on 2024-06-23 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0042_comprobanteasociacion_venta_comprobantes_asociados'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comprobanteasociacion',
            old_name='comprobante_origen',
            new_name='nota_credito',
        ),
        migrations.RenameField(
            model_name='comprobanteasociacion',
            old_name='comprobante_destino',
            new_name='factura_afectada',
        ),
    ] 