# Generated by Django 5.0.1 on 2025-08-07 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0048_agregar_ven_razon_social_a_vista'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='ven_observacion',
            field=models.TextField(blank=True, db_column='VEN_OBSERVACION', null=True),
        ),
    ]
