# Generated by Django 5.0.1 on 2026-06-13 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaAccesoPublico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('nombre_mostrar', models.CharField(max_length=150)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True)),
                ('tenant_asignado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_acceso_publico', to='tenants.empresatenant')),
            ],
            options={
                'verbose_name': 'Cuenta de acceso publico',
                'verbose_name_plural': 'Cuentas de acceso publico',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
