# Generated by Django 5.0.1 on 2026-06-13 06:42

import django.db.models.deletion
import secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceso_publico', '0002_cuentaaccesopublico_admin_tenant_ref'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenPuenteAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=secrets.token_urlsafe, max_length=128, unique=True)),
                ('username_tenant', models.CharField(max_length=150)),
                ('expira_en', models.DateTimeField()),
                ('usado', models.BooleanField(default=False)),
                ('usado_en', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens_puente', to='acceso_publico.cuentaaccesopublico')),
                ('tenant_asignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens_puente_acceso', to='tenants.empresatenant')),
            ],
            options={
                'verbose_name': 'Token puente de acceso',
                'verbose_name_plural': 'Tokens puente de acceso',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
