# Generated by Django 5.2 on 2025-05-12 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_barrio_localidad_cliente_barrio_localidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='barrio',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='localidad',
        ),
        migrations.DeleteModel(
            name='Barrio',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Localidad',
        ),
    ]
