# Generated by Django 5.0.1 on 2025-05-12 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(db_column='PRO_ID', primary_key=True, serialize=False)),
                ('codigo', models.IntegerField(db_column='PRO_CODIGO', unique=True)),
                ('razon', models.CharField(db_column='PRO_RAZON', max_length=50)),
                ('fantasia', models.CharField(db_column='PRO_FANTASIA', max_length=50)),
                ('domicilio', models.CharField(db_column='PRO_DOMI', max_length=50)),
                ('tel1', models.CharField(blank=True, db_column='PRO_TEL1', max_length=12, null=True)),
                ('tel2', models.CharField(blank=True, db_column='PRO_TEL2', max_length=12, null=True)),
                ('tel3', models.CharField(blank=True, db_column='PRO_TEL3', max_length=12, null=True)),
                ('cuit', models.CharField(blank=True, db_column='PRO_CUIT', max_length=11, null=True)),
                ('ib', models.CharField(blank=True, db_column='PRO_IB', max_length=10, null=True)),
                ('cpostal', models.CharField(blank=True, db_column='PRO_CPOSTAL', max_length=7, null=True)),
                ('iva', models.SmallIntegerField(blank=True, db_column='PRO_IVA', null=True)),
                ('contacto', models.CharField(blank=True, db_column='PRO_CONTACTO', max_length=50, null=True)),
                ('impsalcta', models.DecimalField(db_column='PRO_IMPSALCTA', decimal_places=2, max_digits=12)),
                ('fecsalcta', models.DateField(db_column='PRO_FECSALCTA')),
                ('idbar', models.IntegerField(blank=True, db_column='PRO_IDBAR', null=True)),
                ('idloc', models.IntegerField(blank=True, db_column='PRO_IDLOC', null=True)),
                ('idprv', models.IntegerField(blank=True, db_column='PRO_IDPRV', null=True)),
                ('idcap', models.IntegerField(blank=True, db_column='PRO_IDCAP', null=True)),
                ('acti', models.CharField(blank=True, db_column='PRO_ACTI', max_length=1, null=True)),
            ],
            options={
                'db_table': 'PROVEEDORES',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(db_column='STO_ID', primary_key=True, serialize=False)),
                ('codvta', models.CharField(db_column='STO_CODVTA', max_length=15, unique=True)),
                ('codcom', models.CharField(db_column='STO_CODCOM', max_length=15, unique=True)),
                ('deno', models.CharField(db_column='STO_DENO', max_length=50)),
                ('orden', models.SmallIntegerField(blank=True, db_column='STO_ORDEN', null=True)),
                ('unidad', models.CharField(blank=True, db_column='STO_UNIDAD', max_length=10, null=True)),
                ('margen', models.DecimalField(blank=True, db_column='STO_MARGEN', decimal_places=2, max_digits=5, null=True)),
                ('cantmin', models.IntegerField(blank=True, db_column='STO_CANTMIN', null=True)),
                ('idaliiva', models.SmallIntegerField(db_column='STO_IDALIIVA')),
                ('idfam1', models.IntegerField(blank=True, db_column='STO_IDFAM1', null=True)),
                ('idfam2', models.IntegerField(blank=True, db_column='STO_IDFAM2', null=True)),
                ('idfam3', models.IntegerField(blank=True, db_column='STO_IDFAM3', null=True)),
                ('acti', models.CharField(blank=True, db_column='STO_ACTI', max_length=1, null=True)),
                ('proveedor_habitual', models.ForeignKey(blank=True, db_column='STO_IDPRO', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_habituales', to='productos.proveedor')),
            ],
            options={
                'db_table': 'STOCK',
            },
        ),
        migrations.CreateModel(
            name='StockProve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(db_column='STP_CANTIDAD', decimal_places=2, max_digits=15)),
                ('costo', models.DecimalField(db_column='STP_COSTO', decimal_places=2, max_digits=15)),
                ('fecultcan', models.DateField(blank=True, db_column='STP_FECULTCAN', null=True)),
                ('fecultcos', models.DateField(blank=True, db_column='STP_FECULTCOS', null=True)),
                ('proveedor', models.ForeignKey(db_column='STP_IDPRO', on_delete=django.db.models.deletion.CASCADE, related_name='proveedor_stocks', to='productos.proveedor')),
                ('stock', models.ForeignKey(db_column='STP_IDSTO', on_delete=django.db.models.deletion.CASCADE, related_name='stock_proveedores', to='productos.stock')),
            ],
            options={
                'db_table': 'STOCKPROVE',
                'unique_together': {('stock', 'proveedor')},
            },
        ),
    ]
