# Generated by Django 5.0.1 on 2025-05-12 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_proveedor_stock_stockprove'),
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.AutoField(db_column='FAM_ID', primary_key=True, serialize=False)),
                ('deno', models.CharField(db_column='FAM_DENO', max_length=50)),
                ('comentario', models.CharField(blank=True, db_column='FAM_COMENTARIO', max_length=50, null=True)),
                ('nivel', models.CharField(db_column='FAM_NIVEL', max_length=3)),
                ('acti', models.CharField(db_column='FAM_ACTI', max_length=1)),
            ],
            options={
                'db_table': 'FAMILIAS',
            },
        ),
        migrations.AlterField(
            model_name='stock',
            name='idfam1',
            field=models.ForeignKey(blank=True, db_column='STO_IDFAM1', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocks_fam1', to='productos.familia'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='idfam2',
            field=models.ForeignKey(blank=True, db_column='STO_IDFAM2', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocks_fam2', to='productos.familia'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='idfam3',
            field=models.ForeignKey(blank=True, db_column='STO_IDFAM3', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocks_fam3', to='productos.familia'),
        ),
    ]
