# Generated by Django 5.0.1 on 2025-08-18 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_datos_iniciales_productos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='codigo',
        ),
    ]
