# Generated by Django 5.0.1 on 2026-01-28 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_datos_iniciales_alicuotas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaPrecio',
            fields=[
                ('id', models.AutoField(db_column='ID_LISTA_DE_PRECIOS', primary_key=True, serialize=False)),
                ('numero', models.IntegerField(db_column='NUMERO_LISTA_DE_PRECIOS', unique=True)),
                ('nombre', models.CharField(db_column='NOMBRE_LISTA_DE_PRECIOS', max_length=50)),
                ('margen_descuento', models.DecimalField(db_column='PORCENTAJE_AJUSTE_SOBRE_LISTA_CERO', decimal_places=2, default=0, help_text='Porcentaje de descuento (-) o recargo (+) sobre Lista 0', max_digits=6)),
                ('activo', models.BooleanField(db_column='ESTA_ACTIVA', default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, db_column='FECHA_ACTUALIZACION')),
            ],
            options={
                'verbose_name': 'Lista de Precios',
                'verbose_name_plural': 'Listas de Precios',
                'db_table': 'LISTAS_DE_PRECIOS',
                'ordering': ['numero'],
            },
        ),
        migrations.AddField(
            model_name='stock',
            name='precio_lista_0',
            field=models.DecimalField(blank=True, db_column='PRECIO_VENTA_LISTA_CERO_SIN_IVA', decimal_places=2, help_text='Precio de venta base (Lista 0) sin IVA', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='precio_lista_0_manual',
            field=models.BooleanField(db_column='ES_PRECIO_LISTA_CERO_MANUAL', default=False, help_text='TRUE si el precio fue cargado manualmente, FALSE si se calcula desde costo+margen'),
        ),
        migrations.CreateModel(
            name='ActualizacionListaDePrecios',
            fields=[
                ('id', models.AutoField(db_column='ID_ACTUALIZACION_DE_LISTA_DE_PRECIOS', primary_key=True, serialize=False)),
                ('lista_numero', models.IntegerField(db_column='NUMERO_LISTA_DE_PRECIOS')),
                ('porcentaje_anterior', models.DecimalField(db_column='PORCENTAJE_ANTERIOR', decimal_places=2, max_digits=6)),
                ('porcentaje_nuevo', models.DecimalField(db_column='PORCENTAJE_NUEVO', decimal_places=2, max_digits=6)),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True, db_column='FECHA_ACTUALIZACION')),
                ('cantidad_productos_recalculados', models.IntegerField(db_column='CANTIDAD_PRODUCTOS_RECALCULADOS', default=0)),
                ('cantidad_productos_manuales_no_recalculados', models.IntegerField(db_column='CANTIDAD_PRODUCTOS_CON_PRECIO_MANUAL_NO_RECALCULADOS', default=0)),
                ('usuario', models.ForeignKey(blank=True, db_column='USUARIO_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Actualización de Lista de Precios',
                'verbose_name_plural': 'Actualizaciones de Listas de Precios',
                'db_table': 'ACTUALIZACIONES_DE_LISTAS_DE_PRECIOS',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='PrecioProductoLista',
            fields=[
                ('id', models.AutoField(db_column='ID_PRECIO_DE_PRODUCTO_POR_LISTA_DE_PRECIOS', primary_key=True, serialize=False)),
                ('lista_numero', models.IntegerField(db_column='NUMERO_LISTA_DE_PRECIOS')),
                ('precio', models.DecimalField(db_column='PRECIO_VENTA_SIN_IVA', decimal_places=2, max_digits=15)),
                ('precio_manual', models.BooleanField(db_column='ES_PRECIO_MANUAL', default=False, help_text='TRUE si fue cargado manualmente, FALSE si es calculado')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, db_column='FECHA_ACTUALIZACION')),
                ('fecha_carga_manual', models.DateTimeField(blank=True, db_column='FECHA_CARGA_MANUAL', help_text='Fecha en que se cargó manualmente (si aplica)', null=True)),
                ('stock', models.ForeignKey(db_column='ID_PRODUCTO_STOCK', on_delete=django.db.models.deletion.CASCADE, related_name='precios_listas', to='productos.stock')),
            ],
            options={
                'verbose_name': 'Precio de Producto por Lista',
                'verbose_name_plural': 'Precios de Productos por Lista',
                'db_table': 'PRECIOS_DE_PRODUCTOS_POR_LISTA_DE_PRECIOS',
                'indexes': [models.Index(fields=['stock', 'lista_numero'], name='PRECIOS_DE__ID_PROD_65a74b_idx'), models.Index(fields=['lista_numero'], name='PRECIOS_DE__NUMERO__de3ed3_idx'), models.Index(fields=['precio_manual'], name='PRECIOS_DE__ES_PREC_88e6bb_idx')],
                'unique_together': {('stock', 'lista_numero')},
            },
        ),
    ]
