# Generated by Django 5.0.1 on 2025-09-07 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_stock_stock_sto_act_701908_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='stock',
            name='STOCK_STO_ACT_701908_idx',
        ),
        migrations.RemoveIndex(
            model_name='stock',
            name='STOCK_STO_IDP_e69b96_idx',
        ),
        migrations.RemoveIndex(
            model_name='stockprove',
            name='STOCKPROVE_STP_IDS_c6573f_idx',
        ),
        migrations.RemoveIndex(
            model_name='stockprove',
            name='STOCKPROVE_STP_IDP_6bf445_idx',
        ),
    ]
