# Generated by Django 5.0.1 on 2025-05-14 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_familia_alter_stock_idfam1_alter_stock_idfam2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlicuotaIVA',
            fields=[
                ('id', models.AutoField(db_column='ALI_ID', primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, db_column='ALI_CODIGO', max_length=5, null=True, unique=True)),
                ('deno', models.CharField(db_column='ALI_DENO', max_length=20)),
                ('porce', models.DecimalField(db_column='ALI_PORCE', decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': 'Alicuota IVA',
                'verbose_name_plural': 'Alicuotas IVA',
                'db_table': 'ALICUOTASIVA',
            },
        ),
        migrations.AlterField(
            model_name='stock',
            name='idaliiva',
            field=models.ForeignKey(db_column='STO_IDALIIVA', on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='productos.alicuotaiva'),
        ),
    ]
