# Generated by Django 5.0.1 on 2025-05-14 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_alicuotaiva_alter_stock_idaliiva'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='sigla',
            field=models.CharField(blank=True, db_column='PRO_SIGLA', max_length=3, null=True, unique=True),
        ),
    ]
