# Generated by Django 5.0.1 on 2025-08-18 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_remove_proveedor_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='codcom',
        ),
    ]
