# Generated by Django 5.0.1 on 2025-09-07 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_remove_stock_stock_sto_act_701908_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['acti'], name='STOCK_STO_ACT_701908_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['proveedor_habitual'], name='STOCK_STO_IDP_e69b96_idx'),
        ),
        migrations.AddIndex(
            model_name='stockprove',
            index=models.Index(fields=['stock', 'proveedor'], name='STOCKPROVE_STP_IDS_c6573f_idx'),
        ),
        migrations.AddIndex(
            model_name='stockprove',
            index=models.Index(fields=['proveedor'], name='STOCKPROVE_STP_IDP_6bf445_idx'),
        ),
    ]
