# Generated by Django 5.0.1 on 2025-05-14 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_proveedor_sigla'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockprove',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, db_column='STP_FECHA_ACTUALIZACION'),
        ),
        migrations.CreateModel(
            name='PrecioProveedorExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_producto_excel', models.CharField(db_index=True, max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_excel', to='productos.proveedor')),
            ],
            options={
                'verbose_name': 'Precio de producto por proveedor (Excel)',
                'verbose_name_plural': 'Precios de productos por proveedor (Excel)',
                'unique_together': {('proveedor', 'codigo_producto_excel')},
            },
        ),
    ]
