# Generated by Django 5.0.1 on 2025-08-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_remove_stock_codcom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='cuit',
            field=models.CharField(db_column='PRO_CUIT', default=3, max_length=11, unique=True),
            preserve_default=False,
        ),
    ]
