# Generated by Django 5.0.1 on 2025-08-19 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_alter_proveedor_cuit'),
    ]

    operations = [
        migrations.AddField(
            model_name='ferreteria',
            name='permitir_stock_negativo',
            field=models.BooleanField(default=False, help_text='Permite que el sistema permita vender con stock negativo por defecto'),
        ),
    ]
