# Generated by Django 5.0.1 on 2025-05-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_stockprove_fecha_actualizacion_precioproveedorexcel'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockprove',
            name='codigo_producto_proveedor',
            field=models.CharField(blank=True, db_column='STP_CODPROV', max_length=100, null=True),
        ),
    ]
