# Generated by Django 5.0.1 on 2026-01-29 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_precioproductolista_usuario_carga_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precioproductolista',
            name='fecha_carga_manual',
            field=models.DateTimeField(blank=True, db_column='FECHA_CARGA_MANUAL', null=True),
        ),
    ]
