# Generated by Django 5.0.1 on 2026-01-29 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_alter_precioproductolista_fecha_carga_manual'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContadorCodigoBarras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('EAN13', 'EAN-13'), ('CODE128', 'Code 128')], db_column='TIPO_CODIGO', max_length=10, unique=True)),
                ('ultimo_numero', models.BigIntegerField(db_column='ULTIMO_NUMERO', default=0)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contador de Código de Barras',
                'verbose_name_plural': 'Contadores de Códigos de Barras',
                'db_table': 'CONTADOR_CODIGO_BARRAS',
            },
        ),
    ]
