# Generated by Django 5.0.1 on 2025-05-16 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_productotempid_alter_stock_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockprove',
            unique_together={('proveedor', 'codigo_producto_proveedor'), ('stock', 'proveedor')},
        ),
    ]
