# Generated by Django 5.0.1 on 2025-05-16 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_alter_stockprove_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='proveedor_habitual',
            field=models.ForeignKey(db_column='STO_IDPRO', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='productos_habituales', to='productos.proveedor'),
            preserve_default=False,
        ),
    ]
