# Generated by Django 5.0.1 on 2026-01-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_contadorcodigobarras'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='codigo_barras',
            field=models.CharField(blank=True, db_column='STO_CODIGO_BARRAS', help_text='Código de barras asociado al producto', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='tipo_codigo_barras',
            field=models.CharField(blank=True, choices=[('EAN13', 'EAN-13 Interno'), ('CODE128', 'Code 128 Interno'), ('EXTERNO', 'Código externo/escaneado')], db_column='STO_TIPO_CODIGO_BARRAS', help_text='Tipo de código de barras (EAN13, CODE128, EXTERNO)', max_length=10, null=True),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['codigo_barras'], name='STOCK_STO_COD_102ffd_idx'),
        ),
    ]
