# Generated by Django 5.0.1 on 2025-05-16 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_alter_stock_proveedor_habitual'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockprove',
            unique_together={('stock', 'proveedor')},
        ),
    ]
