# Generated by Django 5.0.1 on 2026-01-29 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_stock_codigo_barras_stock_tipo_codigo_barras_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ferreteria',
            name='prefijo_codigo_barras',
            field=models.CharField(blank=True, help_text='Siglas para códigos de barras internos Code 128 (ej: ABC, MIF). Si está vacío, se usa solo el número secuencial.', max_length=10, null=True),
        ),
    ]
