# Generated by Django 5.0.1 on 2025-05-21 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0011_alter_stockprove_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='ferreteria',
            name='situacion_iva',
            field=models.CharField(choices=[('RI', 'Responsable Inscripto'), ('MO', 'Monotributista')], default='RI', help_text='Condición fiscal del negocio/emisor para comprobantes.', max_length=2),
        ),
    ]
