# Generated by Django 5.0.1 on 2026-01-29 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0011_ferreteria_prefijo_codigo_barras'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ferreteria',
            name='activa',
        ),
    ]
