# Generated by Django 5.0.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0012_remove_ferreteria_activa'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='impuesto_interno_porcentaje',
            field=models.DecimalField(
                blank=True,
                db_column='STO_IMP_INTERNO_PORCE',
                decimal_places=2,
                help_text='Porcentaje nominal del impuesto interno que ya viene en el costo (ej. 70 cigarrillos, 26 destilados, 14 cerveza, 8 gaseosas). Solo informativo.',
                max_digits=5,
                null=True,
            ),
        ),
    ]
