# Generated by Django 5.0.1 on 2025-05-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0012_ferreteria_situacion_iva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='margen',
            field=models.DecimalField(db_column='STO_MARGEN', decimal_places=2, default=30, max_digits=5),
            preserve_default=False,
        ),
    ]
