# Generated by Django 5.0.1 on 2025-05-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0013_alter_stock_margen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='acti',
            field=models.CharField(choices=[('S', 'Activo'), ('N', 'Inactivo')], db_column='STO_ACTI', default='S', max_length=1),
            preserve_default=False,
        ),
    ]
