# Generated by Django 5.0.1 on 2026-06-11 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0014_drop_vistas_Stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ferreteria',
            name='direccion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='ferreteria',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('es_principal', models.BooleanField(default=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ferreteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursales', to='productos.ferreteria')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
            },
        ),
    ]
