# Generated by Django 5.0.1 on 2025-06-24 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0015_ferreteria_alicuota_iva_por_defecto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ferreteria',
            name='permitir_stock_negativo',
            field=models.BooleanField(default=False, help_text='Permitir que el stock de productos sea negativo'),
        ),
        migrations.AddField(
            model_name='ferreteria',
            name='punto_venta_arca',
            field=models.CharField(blank=True, help_text='Punto de venta ARCA para comprobantes fiscales', max_length=50, null=True),
        ),
    ]
