# Generated by Django 5.0.1 on 2026-06-12 21:09

import ferreapps.productos.utils.file_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0015_alter_ferreteria_direccion_alter_ferreteria_telefono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ferreteria',
            name='certificado_arca',
            field=models.FileField(blank=True, help_text='Certificado ARCA (.pem) para autenticación con servicios web de AFIP', null=True, upload_to=ferreapps.productos.utils.file_paths.upload_certificado_arca),
        ),
        migrations.AlterField(
            model_name='ferreteria',
            name='clave_privada_arca',
            field=models.FileField(blank=True, help_text='Clave privada ARCA (.pem) para firma digital de comprobantes', null=True, upload_to=ferreapps.productos.utils.file_paths.upload_clave_privada_arca),
        ),
    ]
