# Generated by Django 5.0.1 on 2026-06-12 21:12

import ferreapps.productos.utils.file_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0016_alter_ferreteria_certificado_arca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ferreteria',
            name='logo_empresa',
            field=models.ImageField(blank=True, help_text='Logo de la empresa para comprobantes', null=True, upload_to=ferreapps.productos.utils.file_paths.upload_logo_empresa),
        ),
    ]
