# Generated by Django 5.0.1 on 2025-06-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0016_rename_vista_stock_producto_mayuscula'),
    ]

    operations = [
        migrations.CreateModel(
            name='VistaStockProducto',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('denominacion', models.CharField(max_length=50)),
                ('codigo_venta', models.CharField(max_length=15)),
                ('cantidad_minima', models.IntegerField(blank=True, null=True)),
                ('stock_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('necesita_reposicion', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Vista de Stock de Producto',
                'verbose_name_plural': 'Vistas de Stock de Productos',
                'db_table': 'VISTA_STOCK_PRODUCTO',
                'managed': False,
            },
        ),
    ]
