# Generated by Django 5.0.1 on 2025-06-24 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0016_ferreteria_permitir_stock_negativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ferreteria',
            name='cuit_cuil',
            field=models.CharField(blank=True, help_text='CUIT/CUIL de la empresa', max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='ferreteria',
            name='logo_empresa',
            field=models.ImageField(blank=True, help_text='Logo de la empresa para comprobantes', null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='ferreteria',
            name='razon_social',
            field=models.CharField(blank=True, help_text='Razón social de la empresa', max_length=200, null=True),
        ),
    ]
