# Generated by Django 5.0.1 on 2025-06-24 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0017_ferreteria_cuit_cuil_ferreteria_logo_empresa_and_more'),
        ('productos', '0017_vistastockproducto'),
    ]

    operations = [
    ]
