# Generated by Django 5.0.1 on 2025-01-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0018_merge_20250624_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='ferreteria',
            name='ingresos_brutos',
            field=models.CharField(blank=True, help_text='Ingresos Brutos de la empresa', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ferreteria',
            name='inicio_actividad',
            field=models.DateField(blank=True, help_text='Fecha de inicio de actividad', null=True),
        ),
    ] 