# Generated by Django 5.0.1 on 2026-06-18 08:33

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0019_importacionlistapreciosproveedor'),
    ]

    operations = [
        TrigramExtension(),
        migrations.AddIndex(
            model_name='stock',
            index=django.contrib.postgres.indexes.GinIndex(fields=['deno'], name='stock_deno_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
