# Generated by Django 5.0.1 on 2026-09-30 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0020_stock_stock_deno_trgm_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='precio_lista_0',
            field=models.DecimalField(blank=True, db_column='PRECIO_VENTA_LISTA_CERO_SIN_IVA', decimal_places=2, help_text='Precio de venta final (Lista 0) con IVA incluido', max_digits=15, null=True),
        ),
    ]
