# Generated by Django 5.0.1 on 2025-07-28 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0021_agregar_proveedor_habitual_vista'),
    ]

    operations = [
        migrations.AddField(
            model_name='ferreteria',
            name='arca_configurado',
            field=models.BooleanField(default=False, help_text='Indica si la configuración ARCA está completa y válida'),
        ),
        migrations.AddField(
            model_name='ferreteria',
            name='arca_error_configuracion',
            field=models.TextField(blank=True, help_text='Mensaje de error si la configuración ARCA no es válida', null=True),
        ),
        migrations.AddField(
            model_name='ferreteria',
            name='arca_habilitado',
            field=models.BooleanField(default=False, help_text='Activar/desactivar la emisión automática de comprobantes ARCA'),
        ),
        migrations.AddField(
            model_name='ferreteria',
            name='arca_ultima_validacion',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de la última validación exitosa de la configuración ARCA', null=True),
        ),
        migrations.AddField(
            model_name='ferreteria',
            name='certificado_arca',
            field=models.FileField(blank=True, help_text='Certificado ARCA (.pem) para autenticación con servicios web de AFIP', null=True, upload_to='arca/certificados/'),
        ),
        migrations.AddField(
            model_name='ferreteria',
            name='clave_privada_arca',
            field=models.FileField(blank=True, help_text='Clave privada ARCA (.pem) para firma digital de comprobantes', null=True, upload_to='arca/claves_privadas/'),
        ),
        migrations.AddField(
            model_name='ferreteria',
            name='modo_arca',
            field=models.CharField(choices=[('HOM', 'Homologación'), ('PROD', 'Producción')], default='HOM', help_text='Modo de operación ARCA (Homologación para pruebas, Producción para uso real)', max_length=4),
        ),
        migrations.AddField(
            model_name='ferreteria',
            name='url_wsaa_arca',
            field=models.URLField(blank=True, help_text='URL del servicio WSAA de ARCA (se configura automáticamente según modo)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ferreteria',
            name='url_wsfev1_arca',
            field=models.URLField(blank=True, help_text='URL del servicio WSFEv1 de ARCA (se configura automáticamente según modo)', max_length=255, null=True),
        ),
    ]
