# Generated by Django 5.0.1 on 2025-07-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0022_ferreteria_arca_configurado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ferreteria',
            name='certificado_arca',
            field=models.FileField(blank=True, help_text='Certificado ARCA (.pem) para autenticación con servicios web de AFIP', null=True, upload_to='arca/ferreteria_1/certificados/'),
        ),
        migrations.AlterField(
            model_name='ferreteria',
            name='clave_privada_arca',
            field=models.FileField(blank=True, help_text='Clave privada ARCA (.pem) para firma digital de comprobantes', null=True, upload_to='arca/ferreteria_1/claves_privadas/'),
        ),
    ]
