# Generated by Django 5.0.1 on 2025-08-04 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0023_alter_ferreteria_certificado_arca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='precioproveedorexcel',
            name='denominacion',
            field=models.CharField(blank=True, help_text='Denominación del producto desde Excel', max_length=200, null=True),
        ),
    ]
