# Generated by Django 5.0.1 on 2025-08-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0024_agregar_denominacion_a_precio_proveedor_excel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='acti',
            field=models.CharField(choices=[('S', 'Activo'), ('N', 'Inactivo')], db_column='STO_ACTI', default='S', max_length=1),
        ),
    ]
