# Generated by Django 5.0.1 on 2025-09-15 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialImportacionProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('registros_procesados', models.IntegerField(default=0)),
                ('registros_actualizados', models.IntegerField(default=0)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_importaciones', to='productos.proveedor')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
