# Generated by Codex on 2026-06-18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proveedores", "0001_initial"),
        ("productos", "0019_importacionlistapreciosproveedor"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SolicitudCargaInicialProveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("procesando", "Procesando"),
                            ("completada", "Completada"),
                            ("error", "Error"),
                        ],
                        db_index=True,
                        default="pendiente",
                        max_length=16,
                    ),
                ),
                ("nombre_archivo", models.CharField(max_length=255)),
                ("payload_lote", models.JSONField(default=dict)),
                ("idempotency_key", models.CharField(db_index=True, max_length=64)),
                ("registros_procesados", models.PositiveIntegerField(default=0)),
                ("registros_creados", models.PositiveIntegerField(default=0)),
                ("registros_saltados", models.PositiveIntegerField(default=0)),
                ("mensaje_error", models.TextField(blank=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("iniciado_en", models.DateTimeField(blank=True, null=True)),
                ("finalizado_en", models.DateTimeField(blank=True, null=True)),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitudes_carga_inicial",
                        to="productos.proveedor",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solicitudes_carga_inicial_proveedor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitud de carga inicial de proveedor",
                "verbose_name_plural": "Solicitudes de carga inicial de proveedor",
                "ordering": ("-creado_en",),
            },
        ),
        migrations.AddIndex(
            model_name="solicitudcargainicialproveedor",
            index=models.Index(
                fields=["proveedor", "idempotency_key", "estado"],
                name="proveedores_proveed_519144_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="solicitudcargainicialproveedor",
            index=models.Index(
                fields=["estado", "creado_en"],
                name="proveedores_estado_f455cf_idx",
            ),
        ),
    ]
