# Generated by Django 5.0.1 on 2026-06-18 10:04

import ferredesk_backend.utils.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_solicitudcargainicialproveedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudcargainicialproveedor',
            name='payload_lote',
        ),
        migrations.AddField(
            model_name='solicitudcargainicialproveedor',
            name='archivo_temporal',
            field=models.FileField(blank=True, null=True, upload_to=ferredesk_backend.utils.storage.TenantUploadPath('cargas_iniciales_proveedor', False)),
        ),
    ]
