# Generated by Django 5.0.1 on 2026-02-03 20:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventas', '0003_nuevas_vistas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.AutoField(db_column='MET_ID', primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_column='MET_CODIGO', help_text='Código único del método (ej: efectivo, tarjeta_debito)', max_length=30, unique=True)),
                ('nombre', models.CharField(db_column='MET_NOMBRE', help_text='Nombre visible del método de pago', max_length=50)),
                ('descripcion', models.CharField(blank=True, db_column='MET_DESCRIPCION', help_text='Descripción adicional del método', max_length=200, null=True)),
                ('afecta_arqueo', models.BooleanField(db_column='MET_AFECTA_ARQUEO', default=False, help_text='True si el pago debe contabilizarse en el arqueo de efectivo')),
                ('activo', models.BooleanField(db_column='MET_ACTIVO', default=True, help_text='Indica si el método está disponible para usar')),
                ('orden', models.SmallIntegerField(db_column='MET_ORDEN', default=0, help_text='Orden de aparición en listas desplegables')),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
                'db_table': 'METODO_PAGO',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='SesionCaja',
            fields=[
                ('id', models.AutoField(db_column='SES_ID', primary_key=True, serialize=False)),
                ('sucursal', models.SmallIntegerField(db_column='SES_SUCURSAL', default=1, help_text='Identificador de sucursal')),
                ('fecha_hora_inicio', models.DateTimeField(auto_now_add=True, db_column='SES_FECHA_HORA_INICIO', help_text='Momento de apertura de la caja')),
                ('fecha_hora_fin', models.DateTimeField(blank=True, db_column='SES_FECHA_HORA_FIN', help_text='Momento de cierre de la caja (null si está abierta)', null=True)),
                ('saldo_inicial', models.DecimalField(db_column='SES_SALDO_INICIAL', decimal_places=2, help_text='Monto declarado al abrir la caja', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('saldo_final_declarado', models.DecimalField(blank=True, db_column='SES_SALDO_FINAL_DECLARADO', decimal_places=2, help_text='Monto contado físicamente por el cajero al cerrar', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('saldo_final_sistema', models.DecimalField(blank=True, db_column='SES_SALDO_FINAL_SISTEMA', decimal_places=2, help_text='Saldo teórico calculado por el sistema', max_digits=15, null=True)),
                ('diferencia', models.DecimalField(blank=True, db_column='SES_DIFERENCIA', decimal_places=2, help_text='Diferencia = declarado - sistema (positivo = sobrante, negativo = faltante)', max_digits=15, null=True)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada')], db_column='SES_ESTADO', default='ABIERTA', help_text='Estado actual de la sesión', max_length=10)),
                ('observaciones_cierre', models.TextField(blank=True, db_column='SES_OBSERVACIONES_CIERRE', help_text='Notas adicionales registradas al cerrar la caja', null=True)),
                ('usuario', models.ForeignKey(db_column='SES_USUARIO_ID', help_text='Usuario responsable de esta sesión de caja', on_delete=django.db.models.deletion.PROTECT, related_name='sesiones_caja', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión de Caja',
                'verbose_name_plural': 'Sesiones de Caja',
                'db_table': 'SESION_CAJA',
                'ordering': ['-fecha_hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.AutoField(db_column='MOV_ID', primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], db_column='MOV_TIPO', help_text='ENTRADA para ingresos, SALIDA para egresos', max_length=10)),
                ('monto', models.DecimalField(db_column='MOV_MONTO', decimal_places=2, help_text='Monto del movimiento (siempre positivo)', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('descripcion', models.CharField(db_column='MOV_DESCRIPCION', help_text='Descripción o motivo del movimiento', max_length=200)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, db_column='MOV_FECHA_HORA', help_text='Momento en que se registró el movimiento')),
                ('usuario', models.ForeignKey(db_column='MOV_USUARIO_ID', help_text='Usuario que registró este movimiento', on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_caja', to=settings.AUTH_USER_MODEL)),
                ('sesion_caja', models.ForeignKey(db_column='MOV_SESION_CAJA_ID', help_text='Sesión de caja asociada', on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='caja.sesioncaja')),
            ],
            options={
                'verbose_name': 'Movimiento de Caja',
                'verbose_name_plural': 'Movimientos de Caja',
                'db_table': 'MOVIMIENTO_CAJA',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='PagoVenta',
            fields=[
                ('id', models.AutoField(db_column='PAG_ID', primary_key=True, serialize=False)),
                ('monto', models.DecimalField(db_column='PAG_MONTO', decimal_places=2, help_text='Monto del pago', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('es_vuelto', models.BooleanField(db_column='PAG_ES_VUELTO', default=False, help_text='True si este registro representa el vuelto dado al cliente')),
                ('referencia_externa', models.CharField(blank=True, db_column='PAG_REFERENCIA_EXTERNA', help_text='Referencia externa (ID de transacción, CBU, etc.)', max_length=100, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, db_column='PAG_FECHA_HORA', help_text='Momento en que se registró el pago')),
                ('observacion', models.CharField(blank=True, db_column='PAG_OBSERVACION', help_text='Observaciones adicionales del pago', max_length=200, null=True)),
                ('metodo_pago', models.ForeignKey(db_column='PAG_METODO_PAGO_ID', help_text='Método de pago utilizado', on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='caja.metodopago')),
                ('venta', models.ForeignKey(db_column='PAG_VENTA_ID', help_text='Venta a la que corresponde este pago', on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Pago de Venta',
                'verbose_name_plural': 'Pagos de Ventas',
                'db_table': 'PAGO_VENTA',
                'ordering': ['venta', 'id'],
                'indexes': [models.Index(fields=['venta'], name='PAGO_VENTA_PAG_VEN_8bd33f_idx'), models.Index(fields=['metodo_pago'], name='PAGO_VENTA_PAG_MET_a1d945_idx'), models.Index(fields=['fecha_hora'], name='PAGO_VENTA_PAG_FEC_e44c6d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='sesioncaja',
            index=models.Index(fields=['estado'], name='SESION_CAJA_SES_EST_c73dbd_idx'),
        ),
        migrations.AddIndex(
            model_name='sesioncaja',
            index=models.Index(fields=['usuario'], name='SESION_CAJA_SES_USU_7b7a25_idx'),
        ),
        migrations.AddIndex(
            model_name='sesioncaja',
            index=models.Index(fields=['fecha_hora_inicio'], name='SESION_CAJA_SES_FEC_e45aaa_idx'),
        ),
        migrations.AddIndex(
            model_name='sesioncaja',
            index=models.Index(fields=['sucursal', 'estado'], name='SESION_CAJA_SES_SUC_e5d146_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientocaja',
            index=models.Index(fields=['sesion_caja'], name='MOVIMIENTO__MOV_SES_f33bf7_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientocaja',
            index=models.Index(fields=['tipo'], name='MOVIMIENTO__MOV_TIP_fe3910_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientocaja',
            index=models.Index(fields=['fecha_hora'], name='MOVIMIENTO__MOV_FEC_50dad3_idx'),
        ),
    ]
