# Generated by Django 5.0.1 on 2026-02-05 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0003_pagoventa_monto_recibido'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaBanco',
            fields=[
                ('id', models.AutoField(db_column='cuenta_banco_id', primary_key=True, serialize=False)),
                ('tipo_entidad', models.CharField(choices=[('BCO', 'Banco Tradicional'), ('VIRT', 'Billetera Virtual / CVU')], db_column='tipo_entidad', default='BCO', help_text='Banco o Billetera; se autocompleta desde la clave (7.º dígito: 0=CBU, 1=CVU)', max_length=4)),
                ('nombre', models.CharField(db_column='nombre', help_text='Ej: Banco Galicia, Mercado Pago', max_length=100)),
                ('alias', models.CharField(blank=True, db_column='alias', max_length=50, null=True)),
                ('clave_bancaria', models.CharField(blank=True, db_column='clave_bancaria', help_text='CBU o CVU de 22 dígitos', max_length=22, null=True)),
                ('tipo_cuenta', models.CharField(choices=[('CA', 'Caja de Ahorro'), ('CC', 'Cuenta Corriente')], db_column='tipo_cuenta', default='CC', max_length=2)),
                ('activo', models.BooleanField(db_column='activo', default=True)),
            ],
            options={
                'verbose_name': 'Cuenta Bancaria',
                'verbose_name_plural': 'Cuentas Bancarias',
                'db_table': 'cuenta_banco',
                'ordering': ['nombre'],
            },
        ),
    ]
