# Generated by Django 5.0.1 on 2026-02-05 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0004_cuentabanco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentabanco',
            name='tipo_cuenta',
            field=models.CharField(choices=[('CA', 'Caja de Ahorro'), ('CC', 'Cuenta Corriente'), ('CV', 'Cuenta Virtual')], db_column='tipo_cuenta', default='CC', max_length=2),
        ),
    ]
