# Generated by Django 5.0.1 on 2026-02-05 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0005_alter_cuentabanco_tipo_cuenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoventa',
            name='cuenta_banco',
            field=models.ForeignKey(blank=True, db_column='cuenta_banco_id', help_text='Cuenta bancaria/billetera destino del pago (transferencia/QR)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_venta', to='caja.cuentabanco'),
        ),
    ]
