# Generated by Django 5.0.1 on 2026-02-05 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0006_pagoventa_cuenta_banco'),
        ('productos', '0013_stock_impuesto_interno_porcentaje'),
        ('ventas', '0010_venta_auditoria_cobro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.AutoField(db_column='cheque_id', primary_key=True, serialize=False)),
                ('numero', models.CharField(db_column='numero', max_length=50)),
                ('banco_emisor', models.CharField(db_column='banco_emisor', max_length=100)),
                ('monto', models.DecimalField(db_column='monto', decimal_places=2, max_digits=15)),
                ('cuit_librador', models.CharField(db_column='cuit_librador', max_length=11)),
                ('fecha_emision', models.DateField(db_column='fecha_emision')),
                ('fecha_presentacion', models.DateField(db_column='fecha_presentacion')),
                ('estado', models.CharField(choices=[('EN_CARTERA', 'En cartera'), ('DEPOSITADO', 'Depositado'), ('ENTREGADO', 'Entregado'), ('RECHAZADO', 'Rechazado')], db_column='estado', default='EN_CARTERA', max_length=20)),
                ('fecha_hora_registro', models.DateTimeField(auto_now_add=True, db_column='fecha_hora_registro')),
                ('cuenta_banco_deposito', models.ForeignKey(blank=True, db_column='cuenta_banco_deposito_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheques_depositados', to='caja.cuentabanco')),
                ('pago_venta', models.ForeignKey(blank=True, db_column='pago_venta_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cheques', to='caja.pagoventa')),
                ('proveedor', models.ForeignKey(blank=True, db_column='proveedor_id', help_text='Proveedor al que se entregó el cheque (endoso)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheques_recibidos', to='productos.proveedor')),
                ('usuario_registro', models.ForeignKey(db_column='usuario_registro_id', on_delete=django.db.models.deletion.PROTECT, related_name='cheques_registrados', to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(blank=True, db_column='venta_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cheques', to='ventas.venta')),
            ],
            options={
                'db_table': 'cheque',
                'ordering': ['-fecha_hora_registro'],
                'indexes': [models.Index(fields=['estado'], name='cheque_estado_e33060_idx'), models.Index(fields=['fecha_presentacion'], name='cheque_fecha_p_c78ed4_idx'), models.Index(fields=['venta'], name='cheque_venta_i_8809ce_idx')],
            },
        ),
    ]
