# Generated by Django 5.0.1 on 2026-02-09 18:07

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0010_remove_cheque_endoso_cliente_persona'),
        ('clientes', '0003_cliente_lista_precio_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheque',
            name='comision_cambio',
            field=models.DecimalField(blank=True, db_column='comision_cambio', decimal_places=2, help_text='Comisión cobrada por cambio de cheque', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='cheque',
            name='movimiento_caja_entrada',
            field=models.ForeignKey(blank=True, db_column='movimiento_caja_entrada_id', help_text='Movimiento de caja de entrada asociado al cheque recibido', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheques_recibidos', to='caja.movimientocaja'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='movimiento_caja_salida',
            field=models.ForeignKey(blank=True, db_column='movimiento_caja_salida_id', help_text='Movimiento de caja de salida (efectivo entregado en cambio de cheque)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheques_cambiados', to='caja.movimientocaja'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='origen_cliente',
            field=models.ForeignKey(blank=True, db_column='origen_cliente_id', help_text='Cliente del cual se recibió el cheque (cuando origen_tipo != VENTA)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheques_recibidos_caja', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='origen_descripcion',
            field=models.CharField(blank=True, db_column='origen_descripcion', help_text='Descripción libre del origen (ej: "Cambio de cheque - Juan Pérez")', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cheque',
            name='origen_tipo',
            field=models.CharField(choices=[('VENTA', 'Por venta/recibo'), ('CAJA_GENERAL', 'Por caja general'), ('CAMBIO_CHEQUE', 'Cambio de cheque')], db_column='origen_tipo', default='VENTA', help_text='Tipo de origen del cheque', max_length=20),
        ),
    ]
