# Generated by Django 5.0.1 on 2026-02-10 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0011_cheque_comision_cambio_and_more'),
        ('cuenta_corriente', '0004_cuentacorrienteproveedor_ordenpago_imputacioncompra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheque',
            name='orden_pago',
            field=models.ForeignKey(blank=True, db_column='orden_pago_id', help_text='Orden de pago en la que se utilizó este cheque', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheques_utilizados', to='cuenta_corriente.ordenpago'),
        ),
    ]
