# Generated by Django 5.0.1 on 2026-02-11 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0012_cheque_orden_pago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cheque',
            name='fecha_deposito_real',
            field=models.DateTimeField(blank=True, db_column='fecha_deposito_real', help_text='Fecha/hora real en que se depositó', null=True),
        ),
        migrations.AddField(
            model_name='cheque',
            name='fecha_pago',
            field=models.DateField(blank=True, db_column='fecha_pago', help_text='Fecha de cobro del cheque', null=True),
        ),
        migrations.AddField(
            model_name='cheque',
            name='librador_nombre',
            field=models.CharField(blank=True, db_column='librador_nombre', default='', help_text='Nombre o razón social del emisor del cheque', max_length=100),
        ),
        migrations.AddField(
            model_name='cheque',
            name='tipo_cheque',
            field=models.CharField(choices=[('AL_DIA', 'Al día'), ('DIFERIDO', 'Diferido')], db_column='tipo_cheque', default='AL_DIA', help_text='Al día (cobrable inmediato) o Diferido (fecha futura)', max_length=10),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='fecha_presentacion',
            field=models.DateField(blank=True, db_column='fecha_presentacion', help_text='Fecha real de presentación al banco (se llena al depositar)', null=True),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='origen_tipo',
            field=models.CharField(choices=[('VENTA', 'Por venta/recibo'), ('CAJA_GENERAL', 'Por caja general'), ('CAMBIO_CHEQUE', 'Cambio de cheque'), ('PROPIO', 'Propio (Emitido)')], db_column='origen_tipo', default='VENTA', help_text='Tipo de origen del cheque', max_length=20),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='usuario_registro',
            field=models.ForeignKey(blank=True, db_column='usuario_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cheques_registrados', to=settings.AUTH_USER_MODEL),
        ),
    ]
