# Generated by Django 5.0.1 on 2026-02-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0013_cheque_fecha_deposito_real_cheque_fecha_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheque',
            name='fecha_acreditacion',
            field=models.DateTimeField(blank=True, db_column='fecha_acreditacion', help_text='Fecha/hora en que el banco confirmó la acreditación', null=True),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='estado',
            field=models.CharField(choices=[('EN_CARTERA', 'En cartera'), ('DEPOSITADO', 'Depositado'), ('ACREDITADO', 'Acreditado'), ('ENTREGADO', 'Entregado'), ('RECHAZADO', 'Rechazado')], db_column='estado', default='EN_CARTERA', max_length=20),
        ),
    ]
