# Generated by Django 5.0.1 on 2026-02-14 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0014_cheque_fecha_acreditacion_alter_cheque_estado'),
        ('clientes', '0003_cliente_lista_precio_id'),
        ('cuenta_corriente', '0010_recibo_recibo_rec_total_positivo'),
        ('productos', '0013_stock_impuesto_interno_porcentaje'),
        ('ventas', '0010_venta_auditoria_cobro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cheque',
            name='recibo',
            field=models.ForeignKey(blank=True, db_column='recibo_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheques', to='cuenta_corriente.recibo'),
        ),
        migrations.AddField(
            model_name='pagoventa',
            name='recibo',
            field=models.ForeignKey(blank=True, db_column='PAG_RECIBO_ID', help_text='Recibo al que corresponde este pago', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='cuenta_corriente.recibo'),
        ),
        migrations.AlterField(
            model_name='pagoventa',
            name='venta',
            field=models.ForeignKey(blank=True, db_column='PAG_VENTA_ID', help_text='Venta a la que corresponde este pago', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='ventas.venta'),
        ),
        migrations.AddIndex(
            model_name='cheque',
            index=models.Index(fields=['recibo'], name='cheque_recibo__dce31d_idx'),
        ),
    ]
