# Generated by Django 5.0.1 on 2026-02-18 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0015_cheque_recibo_pagoventa_recibo_alter_pagoventa_venta_and_more'),
        ('cuenta_corriente', '0010_recibo_recibo_rec_total_positivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoventa',
            name='orden_pago',
            field=models.ForeignKey(blank=True, db_column='PAG_ORDEN_PAGO_ID', help_text='Orden de Pago a la que corresponde este pago', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='cuenta_corriente.ordenpago'),
        ),
    ]
