# Generated by Django 5.0.1 on 2026-07-09 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0018_control_fondos_perf_indexes'),
        ('cuenta_corriente', '0010_recibo_recibo_rec_total_positivo'),
        ('ventas', '0016_postventaoperacion_postventaoperacionitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoventa',
            name='postventa_operacion',
            field=models.ForeignKey(blank=True, db_column='PAG_POSTVENTA_ID', help_text='Operacion de postventa asociada al pago', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='ventas.postventaoperacion'),
        ),
        migrations.AddField(
            model_name='pagoventa',
            name='tipo_operacion',
            field=models.CharField(db_column='PAG_TIPO_OPERACION', db_index=True, default='COBRO_VENTA', help_text='Clasifica el sentido economico del pago', max_length=40),
        ),
        migrations.AddIndex(
            model_name='pagoventa',
            index=models.Index(fields=['tipo_operacion'], name='PAGO_VENTA_PAG_TIP_a6894f_idx'),
        ),
    ]
