# Generated by Django 5.0.1 on 2026-06-15 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresatenant',
            name='estado_suscripcion',
            field=models.CharField(choices=[('pendiente_verificacion', 'Pendiente de verificacion'), ('trial', 'Periodo de prueba'), ('activo', 'Activo'), ('suspendido', 'Suspendido'), ('cancelado', 'Cancelado')], default='pendiente_verificacion', max_length=32),
        ),
        migrations.CreateModel(
            name='TokenVerificacionEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens_verificacion_email', to='tenants.empresatenant')),
            ],
            options={
                'verbose_name': 'Token de verificacion de email',
                'verbose_name_plural': 'Tokens de verificacion de email',
            },
        ),
    ]
