# Generated by Django 5.0.1 on 2025-09-15 21:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('comp_id', models.AutoField(db_column='COMP_ID', primary_key=True, serialize=False)),
                ('comp_sucursal', models.SmallIntegerField(db_column='COMP_SUCURSAL')),
                ('comp_fecha', models.DateField(db_column='COMP_FECHA')),
                ('comp_hora_creacion', models.TimeField(auto_now_add=True, db_column='COMP_HORA_CREACION')),
                ('comp_numero_factura', models.CharField(db_column='COMP_NUMERO_FACTURA', help_text='Número de factura completo (formato: Letra-Punto-Número)', max_length=50)),
                ('comp_tipo', models.CharField(choices=[('COMPRA', 'Compra'), ('COMPRA_INTERNA', 'Compra Interna')], db_column='COMP_TIPO', default='COMPRA', max_length=20)),
                ('comp_cuit', models.CharField(blank=True, db_column='COMP_CUIT', max_length=20, null=True)),
                ('comp_razon_social', models.CharField(blank=True, db_column='COMP_RAZON_SOCIAL', max_length=100, null=True)),
                ('comp_domicilio', models.CharField(blank=True, db_column='COMP_DOMICILIO', max_length=100, null=True)),
                ('comp_observacion', models.TextField(blank=True, db_column='COMP_OBSERVACION', null=True)),
                ('comp_numero_factura_proveedor', models.CharField(blank=True, db_column='COMP_NUMERO_FACTURA_PROVEEDOR', help_text='Número interno del proveedor (opcional)', max_length=50, null=True)),
                ('comp_fecha_factura_proveedor', models.DateField(blank=True, db_column='COMP_FECHA_FACTURA_PROVEEDOR', null=True)),
                ('comp_total_final', models.DecimalField(db_column='COMP_TOTAL_FINAL', decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('comp_importe_neto', models.DecimalField(db_column='COMP_IMPORTE_NETO', decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('comp_iva_21', models.DecimalField(db_column='COMP_IVA_21', decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('comp_iva_10_5', models.DecimalField(db_column='COMP_IVA_10_5', decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('comp_iva_27', models.DecimalField(db_column='COMP_IVA_27', decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('comp_iva_0', models.DecimalField(db_column='COMP_IVA_0', decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('comp_verificacion_total', models.DecimalField(db_column='COMP_VERIFICACION_TOTAL', decimal_places=2, editable=False, help_text='Campo calculado: neto + sumatoria IVAs', max_digits=15)),
                ('comp_estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CERRADA', 'Cerrada'), ('ANULADA', 'Anulada')], db_column='COMP_ESTADO', default='BORRADOR', max_length=20)),
                ('comp_fecha_anulacion', models.DateField(blank=True, db_column='COMP_FECHA_ANULACION', null=True)),
                ('comp_idpro', models.ForeignKey(db_column='COMP_IDPRO', on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='productos.proveedor')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'db_table': 'COMPRAS',
            },
        ),
        migrations.CreateModel(
            name='CompraDetalleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdi_orden', models.SmallIntegerField(db_column='CDI_ORDEN')),
                ('cdi_cantidad', models.DecimalField(db_column='CDI_CANTIDAD', decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('cdi_costo', models.DecimalField(db_column='CDI_COSTO', decimal_places=3, default=0, max_digits=13)),
                ('cdi_detalle1', models.CharField(db_column='CDI_DETALLE1', max_length=50)),
                ('cdi_detalle2', models.CharField(blank=True, db_column='CDI_DETALLE2', max_length=40, null=True)),
                ('cdi_idaliiva', models.ForeignKey(db_column='CDI_IDALIIVA', on_delete=django.db.models.deletion.PROTECT, related_name='compras_items', to='productos.alicuotaiva')),
                ('cdi_idca', models.ForeignKey(db_column='CDI_IDCA', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='compras.compra')),
                ('cdi_idpro', models.ForeignKey(db_column='CDI_IDPRO', on_delete=django.db.models.deletion.PROTECT, related_name='compras_items', to='productos.proveedor')),
                ('cdi_idsto', models.ForeignKey(blank=True, db_column='CDI_IDSTO', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compras_items', to='productos.stock')),
            ],
            options={
                'verbose_name': 'Item de Compra',
                'verbose_name_plural': 'Items de Compra',
                'db_table': 'COMPRA_DETAITEM',
                'ordering': ['cdi_orden'],
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('ord_id', models.AutoField(db_column='ORD_ID', primary_key=True, serialize=False)),
                ('ord_sucursal', models.SmallIntegerField(db_column='ORD_SUCURSAL')),
                ('ord_fecha', models.DateField(db_column='ORD_FECHA')),
                ('ord_hora_creacion', models.TimeField(auto_now_add=True, db_column='ORD_HORA_CREACION')),
                ('ord_numero', models.CharField(db_column='ORD_NUMERO', help_text='Número de orden interno (formato: O-0001-00000009)', max_length=50)),
                ('ord_cuit', models.CharField(blank=True, db_column='ORD_CUIT', max_length=20, null=True)),
                ('ord_razon_social', models.CharField(blank=True, db_column='ORD_RAZON_SOCIAL', max_length=100, null=True)),
                ('ord_domicilio', models.CharField(blank=True, db_column='ORD_DOMICILIO', max_length=100, null=True)),
                ('ord_observacion', models.CharField(blank=True, db_column='ORD_OBSERVACION', max_length=60, null=True)),
                ('ord_estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado')], db_column='ORD_ESTADO', default='ABIERTO', max_length=10)),
                ('ord_idpro', models.ForeignKey(db_column='ORD_IDPRO', on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra', to='productos.proveedor')),
            ],
            options={
                'verbose_name': 'Orden de Compra',
                'verbose_name_plural': 'Órdenes de Compra',
                'db_table': 'ORDENES_COMPRA',
            },
        ),
        migrations.CreateModel(
            name='OrdenCompraDetalleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odi_orden', models.SmallIntegerField(db_column='ODI_ORDEN')),
                ('odi_cantidad', models.DecimalField(db_column='ODI_CANTIDAD', decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('odi_detalle1', models.CharField(db_column='ODI_DETALLE1', max_length=50)),
                ('odi_detalle2', models.CharField(blank=True, db_column='ODI_DETALLE2', max_length=40, null=True)),
                ('odi_idor', models.ForeignKey(db_column='ODI_IDOR', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='compras.ordencompra')),
                ('odi_idpro', models.ForeignKey(db_column='ODI_IDPRO', on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra_items', to='productos.proveedor')),
                ('odi_idsto', models.ForeignKey(blank=True, db_column='ODI_IDSTO', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra_items', to='productos.stock')),
                ('odi_stock_proveedor', models.ForeignKey(db_column='ODI_STOCK_PROVEEDOR', help_text='Relación con StockProve para obtener código de proveedor', on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra_items', to='productos.stockprove')),
            ],
            options={
                'verbose_name': 'Item de Orden de Compra',
                'verbose_name_plural': 'Items de Orden de Compra',
                'db_table': 'ORDEN_COMPRA_DETAITEM',
                'ordering': ['odi_orden'],
            },
        ),
        migrations.AddIndex(
            model_name='compra',
            index=models.Index(fields=['comp_fecha'], name='COMPRAS_COMP_FE_70b94f_idx'),
        ),
        migrations.AddIndex(
            model_name='compra',
            index=models.Index(fields=['comp_idpro'], name='COMPRAS_COMP_ID_74b030_idx'),
        ),
        migrations.AddIndex(
            model_name='compra',
            index=models.Index(fields=['comp_numero_factura'], name='COMPRAS_COMP_NU_b7fd4f_idx'),
        ),
        migrations.AddIndex(
            model_name='compra',
            index=models.Index(fields=['comp_tipo'], name='COMPRAS_COMP_TI_0b0ee4_idx'),
        ),
        migrations.AddIndex(
            model_name='compra',
            index=models.Index(fields=['comp_estado'], name='COMPRAS_COMP_ES_6d11f2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='compra',
            unique_together={('comp_numero_factura', 'comp_idpro')},
        ),
        migrations.AddIndex(
            model_name='compradetalleitem',
            index=models.Index(fields=['cdi_idca'], name='COMPRA_DETA_CDI_IDC_9f8ada_idx'),
        ),
        migrations.AddIndex(
            model_name='compradetalleitem',
            index=models.Index(fields=['cdi_idsto'], name='COMPRA_DETA_CDI_IDS_ea3175_idx'),
        ),
        migrations.AddIndex(
            model_name='compradetalleitem',
            index=models.Index(fields=['cdi_idpro'], name='COMPRA_DETA_CDI_IDP_165eda_idx'),
        ),
        migrations.AddIndex(
            model_name='ordencompra',
            index=models.Index(fields=['ord_fecha'], name='ORDENES_COM_ORD_FEC_b28fc2_idx'),
        ),
        migrations.AddIndex(
            model_name='ordencompra',
            index=models.Index(fields=['ord_idpro'], name='ORDENES_COM_ORD_IDP_bfb358_idx'),
        ),
        migrations.AddIndex(
            model_name='ordencompra',
            index=models.Index(fields=['ord_numero'], name='ORDENES_COM_ORD_NUM_4825ad_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ordencompra',
            unique_together={('ord_numero', 'ord_idpro')},
        ),
        migrations.AddIndex(
            model_name='ordencompradetalleitem',
            index=models.Index(fields=['odi_idor'], name='ORDEN_COMPR_ODI_IDO_bb0388_idx'),
        ),
        migrations.AddIndex(
            model_name='ordencompradetalleitem',
            index=models.Index(fields=['odi_idsto'], name='ORDEN_COMPR_ODI_IDS_b62b56_idx'),
        ),
        migrations.AddIndex(
            model_name='ordencompradetalleitem',
            index=models.Index(fields=['odi_idpro'], name='ORDEN_COMPR_ODI_IDP_2de575_idx'),
        ),
    ]
