# Generated by Django 5.0.1 on 2025-08-26 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compradetalleitem',
            name='cdi_detalle1',
            field=models.CharField(db_column='CDI_DETALLE1', max_length=50),
        ),
    ]
