# Generated by Django 5.0.1 on 2026-06-18 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
        ('productos', '0018_stockprove_proveedor_codigo_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='compra',
            index=models.Index(fields=['comp_fecha', 'comp_idpro'], name='COMPRAS_COMP_FE_55c349_idx'),
        ),
        migrations.AddIndex(
            model_name='ordencompra',
            index=models.Index(fields=['ord_fecha', 'ord_idpro'], name='ORDENES_COM_ORD_FEC_c16208_idx'),
        ),
    ]
