# Generated by Django 5.0.1 on 2025-08-28 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_ordencompra_ordencompradetalleitem'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ordencompra',
            new_name='ORDENES_COM_ORD_FEC_b28fc2_idx',
            old_name='ORDENES_COM_ORD_FEC_70b94f_idx',
        ),
        migrations.RenameIndex(
            model_name='ordencompra',
            new_name='ORDENES_COM_ORD_IDP_bfb358_idx',
            old_name='ORDENES_COM_ORD_IDP_74b030_idx',
        ),
        migrations.RenameIndex(
            model_name='ordencompra',
            new_name='ORDENES_COM_ORD_NUM_4825ad_idx',
            old_name='ORDENES_COM_ORD_NUM_b7fd4f_idx',
        ),
        migrations.RenameIndex(
            model_name='ordencompradetalleitem',
            new_name='ORDEN_COMPR_ODI_IDO_bb0388_idx',
            old_name='ORDEN_COMPR_ODI_IDO_9f8ada_idx',
        ),
        migrations.RenameIndex(
            model_name='ordencompradetalleitem',
            new_name='ORDEN_COMPR_ODI_IDS_b62b56_idx',
            old_name='ORDEN_COMPR_ODI_IDS_ea3175_idx',
        ),
        migrations.RenameIndex(
            model_name='ordencompradetalleitem',
            new_name='ORDEN_COMPR_ODI_IDP_2de575_idx',
            old_name='ORDEN_COMPR_ODI_IDP_165eda_idx',
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='ord_estado',
            field=models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado')], db_column='ORD_ESTADO', default='ABIERTO', max_length=10),
        ),
        migrations.AlterField(
            model_name='ordencompradetalleitem',
            name='odi_detalle1',
            field=models.CharField(db_column='ODI_DETALLE1', max_length=50),
        ),
    ]
