# Generated by Django 5.0.1 on 2025-08-28 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_rename_ordenes_com_ord_fec_70b94f_idx_ordenes_com_ord_fec_b28fc2_idx_and_more'),
        ('productos', '0002_vistas_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompradetalleitem',
            name='odi_stockprove',
            field=models.ForeignKey(blank=True, db_column='ODI_STOCKPROVE', help_text='Relación con StockProve para obtener código de proveedor', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra_items', to='productos.stockprove'),
        ),
    ]
