# Generated by Django 5.0.1 on 2025-08-28 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_ordencompradetalleitem_odi_stockprove'),
        ('productos', '0002_vistas_productos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordencompradetalleitem',
            name='odi_stockprove',
        ),
        migrations.AddField(
            model_name='ordencompradetalleitem',
            name='odi_stock_proveedor',
            field=models.ForeignKey(db_column='ODI_STOCK_PROVEEDOR', default=3, help_text='Relación con StockProve para obtener código de proveedor', on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra_items', to='productos.stockprove'),
            preserve_default=False,
        ),
    ]
