# Generated by Django 5.0.1 on 2025-09-07 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0006_remove_ordencompradetalleitem_odi_stockprove_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='ord_observacion',
            field=models.CharField(blank=True, db_column='ORD_OBSERVACION', max_length=60, null=True),
        ),
    ]
